### ISSUE TITLE
Jagged lines, hickups when drawing circles fast

### ISSUE THREAD

**Issue by ombena** [turtletooth/tahoma2d#137]
to be precise, it is impossibbe to draw a perfect circle without it having a straight line. i witnessed theis problem with opentoonz and seemz to have continued with Tahoma.

**To Reproduce**
just try to draw a perfect circle in any level quickly.

**Expected behavior**
slight lagg with imperfect circle (jagged)

**Device Information:**
 - OS: win7 64.
 - Tahoma Version: 1.0.1
 - GPU:  NVIDIA gforce 210 as well as intel hd 4000
![Capture](https://user-images.githubusercontent.com/33788107/92283240-c35dd880-eeff-11ea-8809-4c576c2a7114.JPG)

**Comment by manongjohn** [comment]
Try creating a 3D Profile for Tahoma.exe in the NVIDIA control panel. Make sure to set it to use High Performance GPU since you have 2 video cards.

I usually have to do that to run OT (and likely Tahoma) with any decent performance on my older Win7 machine.

**Comment by turtletooth** [comment]
@ombena Did @manongjohn 's suggestion help?

**Comment by ombena** [comment]
it happens in the 2d room and i am in the stop motion level everything works fine unless i switch to full screen mode.

**Comment by artisteacher** [comment]
At some point, I think in OT, it was reported that decreasing the size of the viewer sometimes increased performance.

**Comment by manongjohn** [comment]
@ombena If you haven't already, follow this video to add Tahoma.exe (and OpenToonz.exe) to the NVIDIA control panel. Though DarrenT used it to fix a render crash, this also fixes performance issues for a number of people, me included: https://youtu.be/QcPVtstcFoE
