### ISSUE TITLE
Debian GNU/Linux Compile Instructions - GNU/Linux StopMotion Feature

### ISSUE THREAD

**Issue by quirinux-so** [turtletooth/tahoma2d#147]
Very interesting, it adds simplicity to software that is somewhat complicated at times. 

Those of us who used Toon Boom Harmony before managed to replace it in GNU / Linux thanks to Toon Boom. Unfortunately we could not replace Dragonframe yet, as the StopMotion tab in GNU / Linux does not work. 

I would love to have an OpenToonz, or Morevna or Tahoma that allow me to do StopMotion. 

At the moment, I cannot find instructions to compile Tahoma on GNU / Linux (the instructions in the Readme are for compiling OpenToonz). 

Sadly, the new version of OpenToonz doesn't even allow you to use the webcam to StopMotion with the old "Camera Capture" feature, which is still there but ... it doesn't work. And in the previous version, it only works when one compiles the program (whereas in snap and appimage formats it doesn't work). 

We really need a professional tool for StopMotion on GNU / Linux. 

a greeting

Charlie Martinez
www.quirinux.org

**Comment by artisteacher** [comment]
If you change the paths from OT to Tahoma, does building succeed? Otherwise, on macOS, the major difference is that I need to export the path for the  turbo-jpeg library before running make.

**Comment by manongjohn** [comment]
I do plan on building an Unbuntu 16.04 AppImage for Tahoma without Canon Support, but I need to address using a BSD compliant opencv first. I also need to find an LGPL ffmpeg distro that can include.

**Comment by manongjohn** [comment]
Oh. The scripts under `ci-scripts/linux` can be used to build locally. Run `travis-install.sh` to install dependencies followed by `travis-build.sh` to create the actual executable.

Those scripts were made for Ubuntu 16.04. More than likely you will need to redo the install script for your distro.

After building, you'll need to create a Tahoma folder with the appropriate exectuables and stuff folder. You can use the `travis-buildpkg.sh` to build an appimage that if you want. Again, modify per your distro.

**Comment by quirinux-so** [comment]
> Oh. The scripts under `ci-scripts/linux` can be used to build locally. Run `travis-install.sh` to install dependencies followed by `travis-build.sh` to create the actual executable.
> 
> Those scripts were made for Ubuntu 16.04. More than likely you will need to redo the install script for your distro.
> 
> After building, you'll need to create a Tahoma folder with the appropriate exectuables and stuff folder. You can use the `travis-buildpkg.sh` to build an appimage that if you want. Again, modify per your distro.

Thank you very much for your cooperation!

I've been looking at the scripts.

I understand that once I have downloaded the source code from once I have downloaded the source code from https: //github.com/turtletooth/tahoma ...

travis-build.sh would be to compile tiff-4.0.3

and so

travis-buildpkg.sh would be to create the .appimage right?

Finally, the travis-install.sh script is the one to modify if you want to get Tahoma to work on Debian.

From what I see, this script installs several libraries. I have not reviewed them, do they differ much from those indicated in the procedure to compile original OpenToonz?

Quirinux GNU/Linux is based on Debian Buster, anything that works there will work on Quirinux too.

A greeting.

**Comment by quirinux-so** [comment]
Thank you very much.

**Comment by jeremybullock** [comment]
We now have a Linux appimage, and I think webcams have been tested to be working with it (at least with version 1.1).

The build scripts have also been updated.

I think that addresses the issues here.

I'm going to close this for now.  Feel free to let me know if there are other things that need to be addressed.

**Comment by quirinux-so** [comment]
That's right, thank you very much: the appimage works perfectly.

Regarding the webcam: it is recognized but, in practice, it cannot be used since the only default resolution that the program assigns to it is too poor.

This topic continues on:

https://github.com/turtletooth/tahoma2d/issues/250

**Comment by manongjohn** [comment]
The latest beta release, dropped yesterday, has some preset resolutions for Linux builds (max of 1920x1080) if you want to check it out .  We can add more if desired.

**Comment by quirinux-so** [comment]
Excellent work, the resolution selector worked perfectly with my Logitech C922, even the manual focus control and all the others.

I do not know other webcam models but, in case my contribution is useful, this camera works at a maximum resolution of 1920x1080 with the mjpg and h264 codecs, while with RGB3, H264, YV12 and YUYV it reaches two more resolutions: 2304x1296, which I sometimes use if I want to photograph a general shot and then crop it and 2304x1536, which I never use.

I have only two suggestions:

-Remove the option "Clean up> Camera capture" (I no longer find it necessary, I think someone else observed it too. On the other hand, it does not work and causes the program to close).
-If this feature https://github.com/turtletooth/tahoma2d/issues/251 or something similar reaches 1.2 I am sure that many more people will adopt the program.

For my part, I will start using it right now.
