### ISSUE TITLE
tahoma 1.0 critical "undefined or empty "SOFTWERE\Tahoma\Tahoma|TOONZROOT""

### ISSUE THREAD

**Issue by Nebulusss** [turtletooth/tahoma2d#166]
![adsdasdas](https://user-images.githubusercontent.com/71219978/93019742-4e4d6b80-f5af-11ea-858f-e3b9cc37d649.png)
i install the .zip of  tahoma, i extract the files, but when i open the tahoma show this (i alredy uninstalled and installed again and keeps on this error):/

**Comment by manongjohn** [comment]
Not sure how you extracted from the zip file, but everything in the zip file needs to be extracted and stay together in 1 folder.  

You are getting that issue because the .exe was separated from the tahomastuff folder.

**Comment by Nebulusss** [comment]
> Not sure how you extracted from the zip file, but everything in the zip file needs to be extracted and stay together in 1 folder.
> 
> You are getting that issue because the .exe was separated from the tahomastuff folder.

i create a new folder and extracted the files, all the files are in the same folder

**Comment by manongjohn** [comment]
Is there a `tahomastuff` as the Tahoma.exe?

**Comment by Nebulusss** [comment]
> Is there a `tahomastuff` as the Tahoma.exe?

Is there a tahomastuff, but i don't find the tahoma.exe

**Comment by manongjohn** [comment]
How are you running it? Did you accidentally move Tahoma.exe outside the folder? It should be in the same directory as tahomastuff (not inside it)

**Comment by Nebulusss** [comment]
![image](https://user-images.githubusercontent.com/71219978/93022251-af307000-f5be-11ea-9f39-9f1f5fd65945.png)
i don't move nothing, i just open the tahoma and show the message"critical error"

**Comment by manongjohn** [comment]
Are you clicking on the Tahoma icon left of the Tahoma you have selected in the image?  It's the one with the T icon.  I'm not sure what that selected Tahoma is or where it came from

**Comment by Nebulusss** [comment]
yes i open the "T" icon and show "crtical error"

**Comment by manongjohn** [comment]
What Windows version are you on? Where did you extract the zip file to?

i am unsure of what is going on.  It almost seems like a permissions thing where it can't see the tahomastuff folder, even though it is right there.  Something is preventing the executable from seeing it, which is why you are having this error.

It's not common, but do you have some sort of anti-virus software that could somehow be restricting it from accessing folders without some permission?

**Comment by Nebulusss** [comment]
im using win 10 64 bits, i extract in a new folder, i will check my antivirus

**Comment by manongjohn** [comment]
Where did you put this new folder?

**Comment by Nebulusss** [comment]
desktop

**Comment by Nebulusss** [comment]
i disable my anti virus and... same error ._.

**Comment by jeremybullock** [comment]
Are you running Tahoma straight from that folder?  It should be seeing the tahomastuff folder in there and not throwing that error.
