### ISSUE TITLE
when i drag an audio file into tahoma it only shows up on 1 frame instead of on the whole column ,how do i fix this

### ISSUE THREAD

**Issue by TerryficANIM8S** [turtletooth/tahoma2d#175]
**Question**
Ask a question related to Tahoma.

**Comment by manongjohn** [comment]
What OS are you on?

**Comment by TerryficANIM8S** [comment]
windows

**Comment by TerryficANIM8S** [comment]
windows

**Comment by manongjohn** [comment]
Forgot to ask, what type of audio file are you trying to load?

**Comment by TerryficANIM8S** [comment]
wav 
its a wav audio file

**Comment by artisteacher** [comment]
Does it happen to be 32bit?

From the manual:
<img width="714" alt="Screen Shot 2020-09-15 at 4 28 07 PM" src="https://user-images.githubusercontent.com/21159116/93261294-8223bf00-f770-11ea-88fa-d848ca4e43f5.png">

**Comment by artisteacher** [comment]
@TerryficANIM8S - does importing audio work as expected if the track is 8 or 16bit?
