### ISSUE TITLE
Menu disappears after deleting new room on macOS

### ISSUE THREAD

**Issue by artisteacher** [turtletooth/tahoma2d#184]
**Describe the bug**
The menu disappears after deleting a room. Upon restarting the menu is back. This happens on OT as well. 

I think it's because on Windows, each room has(or had?) it's own unique menu. In that case, the room's menu should be deleted with the room. On macOS however, there is only one menu that all the rooms share. It should never be deleted.

**To Reproduce**
List steps to reproduce the behavior.
1. Unlock the workspace
2. Create a new room & name it
3. Add a window to the room
4. Switch to a different room
5. Delete the new room

**Expected behavior**

**Screenshots**
Before deleting a room:
![Screen Shot 2020-09-18 at 9 23 40 AM](https://user-images.githubusercontent.com/21159116/93602552-c1c8f180-f990-11ea-9a29-bbc9fbf1e795.png)
After deleting a room:
![Screen Shot 2020-09-18 at 9 23 19 AM](https://user-images.githubusercontent.com/21159116/93602573-cab9c300-f990-11ea-94b8-12494433bad6.png)

**Device Information:**
 - OS: macOS 10.14 & 10.15
 - Tahoma Version: Build from master on 9/11/20

**Comment by artisteacher** [comment]
Creating a new room (after deleting a new room) also brings the menu back.

**Comment by jeremybullock** [comment]
Oh, that's fun.

**Comment by artisteacher** [comment]
That's one way to describe it!
