### ISSUE TITLE
Some windows shrink on open in active room

### ISSUE THREAD

**Issue by artisteacher** [turtletooth/tahoma2d#192]
**Describe the bug**
On macOS, when Tahoma opens, the Timeline, Style Editor, and Stop Motion Controls windows shrink if they are in the active room upon opening. It's possible that other windows could have the same issue, but these are the only ones that are a problem in the default setup. Rooms that were inactive on opening keep their sizes as expected.

**To Reproduce**
1. Open Tahoma after install - the 2D room's Timeline is shorter than the other rooms & the Style Editor is narrower than expected
2. Adjust window sizes to fit the screen better - or switch to the Stopmotion room
3. Close Tahoma
4. Reopen Tahoma - changes to the 2D room are reset if it is active on open; if the stopmotion room is active, the Stop motion controls & Timeline are barely visible.

**Expected behavior**
The widths/heights of windows should not change on opening just because they are in the active room.

**Screenshots**

2D room after adjustments:
<img width="1680" alt="Screen Shot 2020-09-21 at 6 11 49 PM" src="https://user-images.githubusercontent.com/21159116/93826765-f27d8500-fc35-11ea-8333-30591044a020.png">

2D room on install & after reopening if active:
<img width="1678" alt="Screen Shot 2020-09-21 at 6 09 55 PM" src="https://user-images.githubusercontent.com/21159116/93826696-ccf07b80-fc35-11ea-81bc-e15842096430.png">

Stopmotion room if not active on open:
<img width="1676" alt="Screen Shot 2020-09-21 at 6 10 26 PM" src="https://user-images.githubusercontent.com/21159116/93826776-f6a9a280-fc35-11ea-8366-4a296b4db01d.png">

Stopmotion room if active on open:
<img width="1680" alt="Screen Shot 2020-09-21 at 6 13 53 PM" src="https://user-images.githubusercontent.com/21159116/93826927-42f4e280-fc36-11ea-939f-9d47bf27423f.png">

**Device Information:**
 - OS: [macOS 10.14.6 & 10.15.6]
 - Tahoma Version: [master-9-21-20]

**Comment by artisteacher** [comment]
> commenting out lines 524-527 and 552-557 in docklayout.cpp

Does fix the Timeline height issue.

**Comment by jeremybullock** [comment]
I made a PR removing the timeline fixed height stuff.  I'm not sure what's causing the others, but I'll take a look.

**Comment by artisteacher** [comment]
Thanks for looking!

**Comment by artisteacher** [comment]
Timeline's working much better now!

Are the Style Editor & Stop Motion Controls fixed width upon open? They only need to be fixed when resizing the program window...

**Comment by jeremybullock** [comment]
On Windows, they need to be fixed when starting.  Perhaps I can make the resize on start Windows only.
