### ISSUE TITLE
Automatic gap closing when filling for Smart Raster levels

### ISSUE THREAD

**Issue by WolfInABowl** [turtletooth/tahoma2d#206]
This was initially proposed quite a while ago at https://github.com/opentoonz/opentoonz/issues/690
OT/Tahoma's painting tools are pretty great but there is one area where they feel a little limited.

Often when painting, especially if working with binzarized linework, you run into small gaps. These gaps are sometimes only a pixel wide and thus hard to notice. 
Additionally, most of the painting work is done with the Fill Tool so you need to switch tools to fill a small gap/hole.

The ability to detect and close gaps is already present, as can be seen with the Gap Check view mode and the Tape Tool, the former shown with the magenta line.
<img src="https://user-images.githubusercontent.com/42905003/94177355-4df77f00-fe91-11ea-861d-a336dad61792.png" width="250" height="250">
Allowing the Fill Tool to automatically close gaps like RETAS PaintMan would go a long way to improving the overall painting experience as less time will need to be spent finding and closing gaps and more can be spent on actually painting.

**Comment by jeremybullock** [comment]
Closing with pending pr.
