### ISSUE TITLE
Removing a line (or setting the width to zero)?

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#209]
Hello!  I'm wondering if there is a way in Tahoma to erase a selected line between to control points, or at least set the outline width to zero, while keeping the remaining lines intact.

A specific example... I'm drawing a cartoon nose which is basically a rounded W (nostril and bottom of tip of nose).  So, it's an open shape (no outline on the top), visually... but it's a closed shape in reality (so I can fill the nose with the skin colour).

In programs like Moho, you can use a Hide Edge tool to click on any line between two control points to hide it.  Although I'm JUST beginning with Tahoma, I couldn't seem to find anything like that so far.  The Pump tool doesn't seem to allow you to reduce an outline segment to a zero width, either... so I'm not sure if/how to do this.

One workaround, I believe, would be to create an actual open shape, then fill it using a very high gap size setting(?)...

Or maybe create an open shape, then draw a temp 'closing' line, do the fill, and then remove that temp line?  (I seem to recall seeing that sort of technique in videos where people were creating shaded areas within a shape, like the shadowed area at the side of a character's head).

Just wanted to see if there was something I was missing on that.

BTW, I'd greatly welcome anyone pointing to some good tutorials.  I've found maybe two series that are good, but they are limited in their scope (...most vids just kind of do the basics, then stop).

Cheers!

**Comment by artisteacher** [comment]
If you wanted to cleanup overflow vector lines, there is a segment type to the eraser tool that is helpful but in your scenario might erase too much, depending on how the closed shape is formed.  You need to be careful erasing segments from closed vector shapes - they have to stay closed to maintain the fill. That said, there are a few approaches you can take in Tahoma:

1. Draw the open shape & then change the brush size to 0 before you draw a line to close the shape  (0 thickness lines are visible by default (except in render/preview), though visibility can be turned off in preferences)

2. Draw the open shape & draw the line to close the shape with a separate style - then turn the opacity of that style to 0 when you don't want to see the closing line

3. If you've drawn a continuous line for the closed shape, use the knife tool to cut the "closing" segment into it's own stroke - use the fill tool (mode set to line) to change the style to a transparent style

4. Draw your closed shape with "break" enabled - that should make the closing segment of your closed "w" as a loose segment (anywhere there's a sharp corner will have a break in the line) - then use the fill tool (mode set to line) to change the style to a transparent style

5. Draw a closed shape & use a sandwich technique with the FX - there are a few examples of this if you search the OpenToonz Google Group

If you go the route of using a different style, use the number keys to quickly change the active style. If you have more than 10 styles, use the tab key to switch the focus of the shortcuts to the next 10 styles & so on.

**Comment by ladlon** [comment]
Thanks for all that, atristeacher!  Much appreciated.  Some of that is familiar to me, some isn't, so obviously there's some learning to do on my part.

I was actually a bit confused... I tried using the Tape tool to connect the two open ends of the nose (and create a closed shape), but I think I'm misunderstanding the use of the tool.  It DID close the shape, but the new segment was separate and not connected.  Maybe that doesn't matter when you do a fill (...I forgot to try that!), but I assumed it would just make that new line part of the shape.  Ya, still plenty to learn.  Still getting used to this program.

I'll paste your suggestions into a text file, and keep that handy for me to try them out, and see which one becomes my preferred method.

(I'm getting all kinds of weird behavior as I'm doing my first official build/draw of my character... Undo/redo seems to wreak havok, rather than just stepping through the history.  I had certain shapes change colour, or disappear, etc.  A lot of crashing, too...  Then again, I seem to have a real talent for finding obscure bugs in software.)

Great community here so far (I just joined yesterday).  Fast, helpful responses.

**Comment by artisteacher** [comment]
Closed shapes do not necessarily need to be contiguous in order to fill - though sometimes filling is more reliable if they are. There's a join option you can check for the tape tool that you might want to enable if you do want the new segment to be connected.

If you can find any repeatable steps that always cause a crash - no matter how obscure, please report it. Same thing for the undo history - if you realize exactly what is being skipped or etc. in the undo history, please report that too.
