### ISSUE TITLE
Function Curve Editor - lacking horizontal scrolling

### ISSUE THREAD

**Issue by WolfInABowl** [turtletooth/tahoma2d#220]
It is possible to horizontally scroll in many windows, for example, horizontally scrolling in the Timeline/XSheet pans them as is expected.
However, in the Function Editor's Curve Editor window, horizontal scrolling is not possible and instead behaves the same as regular vertical scrolling, zooming in and out. This is true whether I horizontally scroll via Alt + vertical scrolling or by the horizontal scroll buttons on my mouse.

**Comment by artisteacher** [comment]
Very true. I end up zooming out to the cursor position & then repositioning the cursor before zooming in. It works, but is not really intuitive.

**Comment by jeremybullock** [comment]
With the way it is built, a scroll bar isn't really possible, but I did add panning with spacebar.
