### ISSUE TITLE
Is there a way to do a simple (2D offset-based) drop shadow with an FX node?

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#239]
The Cast Shadow thing is powerful and cool... but a bit complex if you just want a traditional 2D offset drop shadow.

Currently, to get around this, I create a Colour Card, use the character (or whatever) as a matte to cut out the shape in the card, then I (rather clumsily) use a FreeDistort simply to shift that over, relative to the character (...as I currently can't seem to find any Tranform/Translate type node that does 2D moves), and then I merge the character with the offset card underneath it via an OverFX node.

A bit convoluted.. although it works.  Would be swell to have a dedicated 2D drop shadow node.

I noticed that nodes that generate things (colour cards, clouds, etc) seem to create levels in the timeline... so, maybe I'd just do a non-offset drop shadow (using the Colour Card and the character as a matte), and then offset it in the timeline?....  maybe?...

Anyway... a dedicated 2D drop shadow thing would still be swell.  ;)

**Comment by artisteacher** [comment]
Another option:
<img width="427" alt="Screen Shot 2020-09-27 at 1 12 35 AM" src="https://user-images.githubusercontent.com/21159116/94356623-957f3600-005e-11eb-9a3c-d42b194f155b.png">
- Perspective distort positions/distorts the shadow (set the anchor point on part of the object, move the vanishing point to control the angle)
- HSV scale can remove the color
- Blur to blur the edges of the level
- Over to keep an unaltered version of the level on top of the shadow version
<img width="124" alt="Screen Shot 2020-09-27 at 1 14 35 AM" src="https://user-images.githubusercontent.com/21159116/94356654-de36ef00-005e-11eb-910b-a00dd206574a.png">

**Comment by ladlon** [comment]
And hello again, artisteacher...  No, I'm talking about a simple (traditional graphic) 2D 'offset shape' type of drop shadow, as opposed to a proper cast shadow (which the CastShadow node handles quite nicely).

Certainly, it can be constructed (as I did) with a few nodes, manually... but I'm just wondering if there isn't a dedicated node for what I'm after, and if not, it's something I think would be helpful (... just to avoid the necessity of building it manually... although, certainly, after doing so, you can probably save it out as a preset or something for next time...).

From what I could see, there doesn't appear to be any node that does 2D transforms.  I have to see if I could just create the 'shadow' (ColourCard cut into the shape of the character/object by using a feed of the character/object as a matte for the card), and then offset it in the timeline/xsheet, since I noticed that seemingly any 'image' generating nodes (cards, fractals, etc) appear as an element in the timeline... most likely because (in the schematic) the output of those nodes is going into the xsheet node... makes sense.  I figure I could then just offset the position of that column, and you'd have a traditional drop shadow.

One of many things to try...

**Comment by artisteacher** [comment]
Yeah, a transform FX would be super helpful.

**Comment by ladlon** [comment]
Okay, cool... I thought I was just completely missing something that was actually there!
