### ISSUE TITLE
Studio Palette commands ignored from Palette window

### ISSUE THREAD

**Issue by artisteacher** [turtletooth/tahoma2d#246]
**Describe the bug**
Any studio palette commands in the Level Palette window don't respond on macOS.

**To Reproduce**
1. Open the Studio Palette Window
2. Choose a project or studio palette & in the context menu choose "Adjust Current Level to This Palette"
3. In the Palette window, try to click on the white squares on the top right corner of each style to make an active link with the studio palette - nothing happens (this also doesn't work in OT)
4. Select the styles & then in the context menu choose "Toggle Link to Studio Palette" - nothing happens (this does work in OT)
5. In the Studio Palette, change one of the colors & then save the palette
6. Back in the Palette window, open the context menu for the equivalent style and choose "Get Color From Studio Palette" - nothing happens (this does work in OT)
7. Choose "Remove Reference to Studio Palette" in the same context menu - nothing happens (this does work in OT)

**Expected behavior**
These commands should all respond.

**Screenshots**
<img width="324" alt="Screen Shot 2020-09-27 at 7 58 38 PM" src="https://user-images.githubusercontent.com/21159116/94379068-f6108080-00fb-11eb-853f-f81a5ee19931.png">

**Device Information:**
 - OS: macOS
 - Tahoma Version: master 9/26/20

**Comment by manongjohn** [comment]
Do you still have that hover issue on macOS? I wonder if it could be somehow related.

Something odd/similar I also noticed for macOS, today, on xsheet/timeline for Sound columns. The sound thumbnail acts as a play button for the audio. In Windows you can click on it to playback the audio. I noticed on macOS it doesn't work.

**Comment by artisteacher** [comment]
Yeah, hovering is still fussy - even without a tablet. It seems to be most unreliable directly after using the brush. Afterwards you need to click in whichever area for hovering to work/the cursor to change. Ie. after using the brush, I need to click down on the boundary between the windows for the change width icon to pop up.

Pressing the sound icon is working for me to play an audio track - at least on macOS 10.15.6 & 10.14.6. I can check on 10.13 on Tuesday. In case the format matters, I've just tested .wav tracks so far.

**Comment by artisteacher** [comment]
https://github.com/turtletooth/tahoma/issues/217#issuecomment-699721626
It looks like the link toggle can be an issue in Windows too, but it sounds inconsistent.

**Comment by manongjohn** [comment]
Admittingly it's been a long while since I've used a studio palette, though I do remember playing with it at some point in the past to understand it better.

Clicking on the little white box doesn't do anything. It's just an indicator. I went back to version 1.2.1 (windows) and clicking on the white box in the corner doesn't toggle anything.  Would be nice though.

**Comment by manongjohn** [comment]
I just tested the context menu options on 10.15 VM and they worked for me using the 1.0.1 Sep 4 build

**Comment by manongjohn** [comment]
Ok I take that back a bit. it seems to happen somewhat inconsistently.   Sometimes doing a New Scene fixes it when it is broken, or breaks it if it was working.

**Comment by artisteacher** [comment]
I haven't been able to get it working at all. Was just testing older builds (through Sep. 5th) & it fails on all of them for me. At least that rules out some of the more recent palette updates.

**Comment by manongjohn** [comment]
This is an issue in Windows too.  I can get it consistently. I know why the commands aren't working.  The commands aren't being enabled properly after adjusting the level because it still thinks it's a global palette after the adjustment.

Looking to see what broke it.

**Comment by artisteacher** [comment]
Thank you!

Honestly the whole studio palette workflow seems a little convoluted to me. Even when the context menu commands work, it should be simpler to have palettes link together. If we could choose an existing studio/project/default palette when creating a level & choose for it to be linked or unlinked, that could save a lot of time from the beginning.
![palette_linking](https://user-images.githubusercontent.com/21159116/94386313-5eb82700-0115-11eb-945c-b1821a3c5125.png)
