### ISSUE TITLE
Pegs question

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#247]
Hi.  So, I understand pegs and everything fine.  I'm just curious about something...

I was watching a good tutorial series on OpenToonz, by a guy who was clearly talented and had loads of real-world experience, and at one point, he said that animating the 'sheets' directly was 'bad form', and that pegs should always be used (for all levels).

While I get 'conceptually' why this might be the case, I really didn't see any technical reason why this should be followed.

Certainly for grouping things, and specific instances... but otherwise, I didn't see (in a digital realm) any real negative aspects to animating the 'sheet' itself.

I'm curious what others here feel, and if there IS actually some reason (other than real-world tradition/realities) to never animate the sheet directly, and always use pegs.

**Comment by artisteacher** [comment]
There are always certain behaviors that are considered best practices - ie. naming something descriptively, keeping assets organized & etc. You can certainly animate successfully without following many best practices. Not following them can often slow you down or negatively impact someone else's understanding/access. 

That said, the great thing about working digitally is that we can learn from the past and build upon it when it is relevant. At the same time, we don't have to be limited by the restrictions of the physical world & how things used to work. Choose the techniques that works best for you & your vision. If we all limited ourselves to working the exact same way, innovation would never happen.

As far as pegboards go, the question is, what/how you are animating? If I'm drawing each frame myself & not tweening, I don't see how a pegboard is necessary. Same thing for doing actual stop motion - why do I need a pegboard for photos? However if I'm tweening movement for a group of drawings that is largely in sync - ie. a school of fish, a pegboard is a huge time saver. If  there's the possibility that my drawings might be in sync for a time, a pegboard is probably the way to go.

**Comment by ladlon** [comment]
Certainly, and I've fallen into both methods over the course of my career.

It seems, though, that pegs serve only (as far as I can see) as a null or handle.... so, as you say, if you have a number of items you want to move together, you can parent them to a peg... or simply one of the items themselves, which I tend to do in cases where there is an obvious 'parent'... or even if there is a suitable parent object that is physically large (and easy to grab).

Seems to me, though, between using pegs vs using one of the items as a parent for the group, the latter is superior, in that it seems that pegs do not display keys in the timeline/xsheet... which seems a big disadvantge, assuming there's no advantage to using pegs over a parent object in the group.  So, that's why I was puzzled this guy seemed adamant that it was poor form to not use pegs for everything.

The only other use for pegs (although, again, you could do this just as well with an empty/invisible column/item as well), is if you wanted to add secondary 'handle' on the item, to apply animations to, so they would be separate from the main animation.  And, again, it would seem a 'null/handle' column would be better than a peg, as it displays the keys, whereas a peg doesn't seem to.

So, ya, I'm just kind of asking, just to make sure there's not some technical (ex. software limitation/quirk) reason for using pegs over parenting some other column/item... especially considering the keyframe display thing.  I just wanted to make sure there was not some additional advantage/feature of pegs, other than them simply being a null object (to put it in 3D anim terms).

I was kind of surprised that pegs don't even show up at an item/column in the timeline/xsheet, like some other nodes do (ex. clouds, etc).

**Comment by artisteacher** [comment]
I guess the downside to using an item as a parent is that the parent item can't be animated individually. If a peg is the parent, everything attached to it can still be animated for independent movement.

I'm not aware of a technical limitation, though it's possible there is one. 

For a long time, even the camera wasn't visible in the Timeline/Xsheet.
