### ISSUE TITLE
Rename to Tahoma2D?

### ISSUE THREAD

**Issue by jeremybullock** [turtletooth/tahoma2d#249]
For ease of discovery, should the official name be Tahoma2D? I don't want to stray too far from the Tahoma name, but giving it the same name as a font may not help discovery.  On the other hand, Blender seems to have figured it out.

**Comment by manongjohn** [comment]
It wouldn't hurt, though it also reminds me of "Pencil2D" also.

In general I think it would also help say what Tahoma is. "Tahoma" could be anything. "Tahoma2D" kind of makes it art related.

**Comment by DoctorRyan** [comment]
I know it would help in Google's algorithms.  I have been doing periodical
testing on the search engine and it still brings up alot of other things
connected to the word Tahoma.  The 2d might be enough to give it that extra
identity when people go looking for it.  (However discovery of the product
at this stage of development has been pretty good regardless.)

**Comment by DarrenTAnims** [comment]
I agree, for discovery, Tahoma brings up other results when searching. So either Tahoma2D or TahomaToonz (as it's based on the Toonz code) would be good.

**Comment by artisteacher** [comment]
I'd go with Tahoma2D over TahomaToonz.

**Comment by artisteacher** [comment]
As far as Blender goes, it's been around long enough that it's the top search result. However when searching for something specific about Blender, you often still need to add 3d or cycles or etc. to get relevant search results.

**Comment by ladlon** [comment]
I agree on something like Tahoma2D.  Currently, not only do you get results on the font, the city (original name) and anything related to that city, and even a home automation system.  I always have to search for 'Tahoma opentoonz', just to get the website or related items to show up in the results.

**Comment by jeremybullock** [comment]
Tahoma2D it is.  I'll be renaming the website.  Anyone who has cloned this repo will need to update the location in git.  Sorry for the hassle.

**Comment by DarrenTAnims** [comment]
ok. And what's the Twitter name that you want us to use? Maybe pop that into the About box and have a twitter panel on your site showing recent tweets using the name?

**Comment by jeremybullock** [comment]
There is a tahoma2d twitter account already that I need to start sending updates on.  And I'll start using the hashtag #tahoma2d.  Good question @DarrenTAnims

**Comment by jeremybullock** [comment]
Website is rebranded.

**Comment by manongjohn** [comment]
Out of curiosity, with the rebranding in mind, thought's on changing folder/executable/application names to `Tahoma2D`?

If you are going to do it, it's probably best to do it now.

**Comment by manongjohn** [comment]
For those that want to update your fork's repo name to match this repo, remotely and locally, you can do the following without having to refork/reclone.  Recommended so you don't lose any unpublished local branches you have:

1. On Github, go to your fork's and change the name from `tahoma` to `tahoma2d`
2. On local repo
- Optional step: Rename your `tahoma` repository folder to `tahoma2d`
- Change your origin as follows:
```
git remote set-url origin https://github.com/xxxx/tahoma2d
```
- If you renamed the `tahoma` folder to `tahoma2d`:
  - Windows users: Redo the `cmake` step pointing to the renamed directory to rebuild the VS project file.
  - macOS/Linux users: `rm -rf toonz/build` directory
  - macOS Xcode builds: Redo the `cmake` step to rebuild the Xcode project file

**Comment by jeremybullock** [comment]
Awesome.  Thanks for sharing that info with folks.
