### ISSUE TITLE
Camera Resolution in GNU/Linux

### ISSUE THREAD

**Issue by quirinux-so** [turtletooth/tahoma2d#250]
I am very in awe of the stopmotion tab in GNU / Linux and the fact that my webcam was recognized. But I still can't use it as the resolution is very poor.

References:

http://my.opendesktop.org/s/yoymjpiHLfo4QRD

https://my.opendesktop.org/s/ofTJ8dZ2qSbSETe

The Tupi Desk developer managed to incorporate the camera into his application and it works well, perhaps reviewing the source code of it may be useful:

https://github.com/xtingray/tupitube.desk

**Comment by manongjohn** [comment]
English please. 😁

**Comment by jeremybullock** [comment]
Unfortunately, I can't even look at that code.  It is under the GPL and is fully incompatible with Tahoma.  Even if I were to try and get ideas from the code, that would ethically violate the GPL.

**Comment by manongjohn** [comment]
I noticed on the Linux version that the Resolution dropdown is empty. Doing a little research, there apparently is/was a QT bug relating to obtaining webcam resolutions on Linux. I need to see if a later QT version fixes it or if there is a posted workaround for it. I currently build on QT 5.9 and don't want to go too high because later versions of QT on linux have other problems that would impact drawing on Tahoma.

**Comment by jeremybullock** [comment]
We can probably find an alternative for getting resolutions on linux that doesn't use Qt for polling resolutions.  I'll see what I can find.  
@manongjohn Does your linux vm see your webcam?

**Comment by manongjohn** [comment]
Yes, my VM sees my laptop's integrated webcam.

**Comment by jeremybullock** [comment]
Awesome.  I don't think OpenCV will supply resolutions, but we could populate the list on linux with the most common resolutions as a quick fix.

**Comment by quirinux-so** [comment]
It's a great idea! Probably for Tupi they have solved it the way you say. The most serious problem with OpenToonz is that it is setting as the only resolution, by default, one really too low and the dropdown selector does not show any options. If you could put 1280x720, 1290x1080 would be great, and it would be beyond cool to add 2304x1296 (since in StopMotion it is usual to work in a larger area and then crop the planes). Regarding the latter, in Guvcview what I notice is that -at least my webcam- only works in 2304x1296 with the YUIV-YUIV 4: 2: 2 codec that, in general, presents a certain lag with my hardware, in all the resolutions, while MJPG does not support 2304x1296 but works very smoothly with 1280x720 and 1290x1080 (which does support them).

Regarding Tupi, excuse me, I thought OpenToonz was released under the GPL.

I wonder if you could contact Gustav, its developer (Tupi has only one developer) on my behalf - who knows me - and request some kind of authorization to take a look at his code.

I made an installer deb for Tupi, if you want you can unzip and check just in case the issue is related to the libraries it installs:

http://my.opendesktop.org/s/Zrce88JXLRjiqXF

I can cite another reference: I have the memory that OpenToonz 1.3 installed from the Multimedia repositories did allow to choose the resolution.

A trick that I do sometimes, with some programs, is to open guvcv, configure my camera, close it and then the camera is already configured for other applications (like google meet). This trick did not work with Taoma.

Yes it does, in Taoma the manual focus of my webcam works perfectly, from the settings tab (good job!)

Anyway, I think that with what you propose it would already be solved and I will look forward to a new release. My intention is to incorporate it pre-installed in Quirinux 2.0, soon to be released (with the .appimage it is enough for me). Thousands of thanks.

**Comment by quirinux-so** [comment]
@jeremybullock I am seeing that the program is released under license BSD 3-Clause "New" or "Revised" License and while the original BSD was GPL incompatible, the new or revised one is compatible! 
At least that's what I understood after reading this:
https://www.gnu.org/licenses/gpl-faq.html
(Maybe I'm wrong)

**Comment by quirinux-so** [comment]
Feature available in Tahoma2D version 1.1 Beta 1. THANKS !!! :-)
