### ISSUE TITLE
Increment editor tool for StopMotion (like DragonFrame)

### ISSUE THREAD

**Issue by quirinux-so** [turtletooth/tahoma2d#251]
Increment editor is a tool widely used by StopMotion animators and it is the main reason why they prefer DragonFrame over any other software, be it free or proprietary.

If they could incorporate it, I know a lot of people who would start using OpenToonz.

Reference: https://vimeo.com/353672737

**Comment by jeremybullock** [comment]
I will probably be adding something similar during to that during the 1.2 build cycle.

**Comment by jeremybullock** [comment]
This has been added.

**Comment by quirinux-so** [comment]
> This has been added.

Sorry, I can't find it in version 1.1. Where would you be (Note that I am not referring to a function editor but to the stop motion editor that allows you to draw curves on the photograph, indicating the number of intermediates. Then, the utility automatically calculates the distance of these intermediates based on the desired acceleration and deceleration. ). Or do you mean the next version 1.2?

**Comment by manongjohn** [comment]
It will be in 1.2. In Tahoma, it is an enhancement to Motion Path. A new Motion Path Panel was created. See PR #420
