### ISSUE TITLE
Crashing randomly after a few undo's 

### ISSUE THREAD

**Issue by ALPHABRINE** [turtletooth/tahoma2d#252]
Hey Bruv, Tahoma randomly crashes alot when testing out the my paint brushes, especially the soft blur like brush, thats when i try to undo after some time, it just closes.
Its kind of hard to recreate because it just happens out of the blue, but mostly on the soft round blur-like brushes(all of them) And also both opentoonz and Tahoma slow down when the brushes get very big, 
but it makes it hard to paint soft shadows on large areas...

I5 8th gen
12GB RAM
Nvidia GTX 1050 ti 4GB video memory
windows 10 home edition
Tahoma 1.0
Thanks

**Comment by artisteacher** [comment]
If you are using blur brushes, is this happening on a raster level? Does it happen on smart raster levels too?

**Comment by ALPHABRINE** [comment]
Since only raster and smart raster levels are tye only ones with blur brush
functionality, it only happens on them, as soon as the brush gets close to
1/5 of the canvas size, there is a massive lag, which is wiered because in
Photoshop and krita it stays smooth..
But in toon boom it just straight up lags till it even crashes sometimes,
then the issue about the undo crashing just happens randomly, its very hard
to predict when pressing
ctrl + Z will make opentoonz crash.

**Comment by jeremybullock** [comment]
I'm going to close this until we are able to duplicate this reliably.
