### ISSUE TITLE
Relational expressions between animatable attributes of two different columns?

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#259]
I see that Tahoma can utilize expressions for interpolations, but I'm wondering if it can specifically do relational expressions between attributes of two different columns/items.

For example:

Positional X-Value of column1 = 8 x Y-Value of column2    (So that the Y value of column2 is being driven by the current value of the X value of column1)

If so, could someone give me a sample of such an expression, making sure it is between two different columns, so I could get an idea of the proper syntax that Tahoma uses?

I read over the expression section in the manual, but I'm still a bit fuzzy on how Tahoma addresses specific columns, outside of the 'host' one of the expression.  I'm assuming it works similar to that of After Effects, but am not sure if there's any differences in syntax.

I'm wanting to do a sort of parallax-based thing, but am trying to set it up so I just move one item, and the others will be automatically moved the proper relative amount, based on the first object's new value.

**Comment by WolfInABowl** [comment]
To reference another column in an expression, you can use the col`n` syntax e.g. `col2.x` refers to the x position of column 2.
This syntax is the same for cameras and pegbars e.g. `cam1.scale`, `peg1.pos`
So if I wanted the y position of Column1 to be equal to the rotation of Column2, I would add an expression interpolation to Column1's y parameter and use the expression `col2.rot`

You can also refer to values within an FX node, here you use this syntax `fx.NodeName.Parameter` e.g. `fx.FractalNoiseIwa01.Complexity`

When you reference a parameter, you can offset the frame you are looking at e.g. `col2.x(f-1)` will add a 1 frame delay to the value

**Comment by ladlon** [comment]
Thanks, WolfInABowl.  Ya, I was impressed with the ability to offset the target frame.  I haven't seen that sort of thing before.

The syntax has a bit of an ActionScript kind of object-based vibe.  Seems to make sense.

I'll have to tinker around wtih that, now that I know about the access system for other columns.

**Comment by ladlon** [comment]
Cool, that's working good.

The only thing I'm a bit confused about... It seems you have to set at least two keyframes for the 'slave' item (the second item, the one affected by the expression) before you are even able to apply an expression (the Interpolation pulldown gets greyed out).

While that mades sense for the other interpolation modes (since you NEED at least two keyframes to actually interpolate between), I don't understand why you need to create two (ultimately pointless) keyframes just to bring up the ability to apply an expression.

If the slave object is to be entirely driven by an expression (ex. match the x positional values of the 'master', then why not be able to apply the expression right away, as the item shouldn't need any keys, since the positional values will be determined entirely by the expression, which pulls the value from the master object.  Once you apply the expression, the two 'dummy' keys just become irrelevant and ignored anyway, since they didn't have a purpose to begin with.

**Comment by jeremybullock** [comment]
This question would be better to be asked on the new Google group or in the Tahoma2D discord.
https://groups.google.com/g/tahoma2d
https://discord.gg/4HUXF6F

In the interest of clearing up the issue list here on GitHub, I'll be recommending this on a number of questions in the issues.
