### ISSUE TITLE
Update Shortcuts button [NOT NEEDED]

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#262]
Easy one...  (I'd think...)

In the Shortcut Edit window, along with the Save button (to save your custom shortcut configuration), it would be great to have a 'Update Shortcut' button beside it, which simply saves the currently active shortcut config/file, so you don't have to keep typing the name and respond to the 'Overwrite' warning every time you add a new shortcut to your current custom shortcuts.  Simple one click action to save the Shortcuts file.

**Comment by jeremybullock** [comment]
You don't need to hit save when changing shortcuts, unless you want to export them.  Are you exporting your shortcut settings?

**Comment by ladlon** [comment]
Nope.  Does it retain the shortcuts when you shut down (if you just edit the shortcut list, and don't hit Save)?

If so... cool.  It seems I was unnecessarily hitting Save then.  I thought that was how you'd update the shortcut config!

**Comment by jeremybullock** [comment]
It automatically updates.

**Comment by ladlon** [comment]
Done deal!  Thanks.  I'll close this one, too.
