### ISSUE TITLE
Interactive span adjustment

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#263]
I'd love to see this feature, for easy/fast editing of spans (cells containing a hold of a drawing)...

-Click on any cell within a timeline/xsheet span
-Use the mouse wheel (and maybe an alternate, like an up/down mouse drag, for those who don't have a wheel) to interactively expand/contract the span (add/remove cells)... including contracting it down so that there's no hold cells (just the initial drawing)

(This would also work to expand a single cell into a span)

I see it working well with the mouse wheel, although ideally you'd have it configurable so users could choose their own preferred/possible methods (mouse drag, keys, etc).

**Comment by jeremybullock** [comment]
There is already extend frame (') and decrease hold (;)
Is that close to what you are looking for?

**Comment by ladlon** [comment]
Sounds like it!

I just tried it, but only the extend works... Must be a lost shortcut.

I tried to find it in the shortcut editor, but couldn't.  Doesn't appear to be anything using Extend or Decrease, nor anything in the XSheet section... Where would I find it in the Shortcut Editor?

**Comment by jeremybullock** [comment]
It's decrease step.

**Comment by ladlon** [comment]
Yep, just found it....  In the Cells section (...sneaky!).

Yup, that is exactly what I needed.  Awesome.  Thanks, Jereremy.  I'll close this thread.
