### ISSUE TITLE
Weird render issue with plastic arm [SOLVED]

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#266]
Hi.  I was playing around with the Plastic tool, where I have a regular 'cutout' style character with an arm that has a PlasticTool mesh applied (and a hand object attached to it).

Everything seems fine when it plays back in Tahoma, but when I render it, it's quite broken, and I'm curious what it might be.

I've included a screenshot that shows the scene in Tahoma, the rendered clip, and the schematic.  BTW, I have a faux drop shadow effect, so that's some of the grey shapes you see in the render.

Any theories?

![MeshRenderissue](https://user-images.githubusercontent.com/71803483/94770340-629cb100-0382-11eb-844a-d4937cf5d44e.JPG)

**Comment by jeremybullock** [comment]
What happens if you take the hand away from being parented to the mesh?

**Comment by jeremybullock** [comment]
What render options are you using?

**Comment by RattusaurusRex** [comment]
This looks like what happens if you choose the 16 bit render option.

**Comment by artisteacher** [comment]
Known issue with 16bit plastic render. https://github.com/opentoonz/opentoonz/issues/2563

Switch to 8bit & it will be fine.

**Comment by ladlon** [comment]
Hi, guys.  Thanks for the responses.

@RattusaurusRex: I think you nailed it.  I DID use 16 bit rendering, and since it is apparently a known bug (based on artisteacher's link) then I'm fairly confident that's going to be it.  I have to give that a try.

@jeremybullock: I'll test out the hand parenting if the 16bit thing proves not to be the factor, and let you know.

I'm curious...  What does rendering in 16bit give you?  Less colour banding?  An alpha channel?

I just instinctively switched my default render setting to 16bit, figuring 8bit might just be for less powerful machines or something.

@artisteacher: I'll try that.  Thanks!

I'm glad that seems like it might be resolved.  The only other thing I thought it might be, is that the left arm (with the mesh) was built by copying the geometry of the right arm, and doing a -100 scale on it.  I'm assuming the scale is 'destructive' and essentially the geometry is frozen in that new state, rather than it being a live transform (...otherwise, I thought maybe that live transform might have been causing that...).

Okay, I'll look into that in a bit, after I've had my breakfast.
