### ISSUE TITLE
Change parent from the xsheet dropdown is hidden.

### ISSUE THREAD

**Issue by jeremybullock** [turtletooth/tahoma2d#272]

**Comment by artisteacher** [comment]
The target area to expose the parent options is also narrower than I'd expect.
<img width="79" alt="Screen Shot 2020-10-02 at 9 39 37 AM" src="https://user-images.githubusercontent.com/21159116/94929647-5eac8400-0493-11eb-9d06-ef4396a21ae9.png">

**Comment by jeremybullock** [comment]
That is narrow because you can also change the connected port from there too.  If you have something parented to a column, you should see the port and clicking that will drop down port options.

**Comment by jeremybullock** [comment]
Reopening to remind myself to fix a few things here.
