### ISSUE TITLE
Include Save (Project/Global) Palette as a keyboard shortcut

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#274]
Hi.  I'm spending a lot of time adding to and making adjustments to my project palette (which I have all my levels using and linked to)... and to see the changes, I need to save the project palette via the menu at the bottom right of the Global Palettes window.

A great time saver would be to be able to set that save as a keyboard shortcut, so I can frequently update the colours in the project without having to use the mouse and the menu pulldown.

I see there is a Save Palette item in the shortcuts list, but it appears it might be the local (level) palette(s), rather than the global one... 

Having it as a shortcut would definitely help speed up the colouring process for me.

**Comment by jeremybullock** [comment]
I just made this.  Saving in the studio palettes is done pretty regularly, so I added a shortcut, and brought the save button out of the drop down menu and into the bottom menu, for quicker access.

**Comment by ladlon** [comment]
Awwwwwsome!  Thanks, jeremybullock!
