### ISSUE TITLE
Ability to make lines between control points different colours

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#279]
Title pretty much says it all... I'm thinking that you'd select a line segment between to control points, and be able to set the colour, while not affecting the other outlines.  This would be nice not only for aesthetic purposes, but also to easily hide some of the sections of the outline (by making it, for example, the same colour as the fill).

**Comment by jeremybullock** [comment]
This is not currently feasible with the way vectors are coded.
