### ISSUE TITLE
Current 'best' way to create this unclosed shape?

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#281]
Sorry, I'm still a bit foggy on the best way to do this sort of thing.

Here's a very simple example....

If I wanted to create a rectangle (black outline, green fill), but have the top edge not have an outline (visibly, at least), what is the current, best way to do this?  (Assume that I want to do this with the rectangle tool, as opposed to just freehand drawing a rectangle with the brush)

I can think of a few ways, but none of them are particularly easy, and it seems like there's an easier way.

**Comment by RattusaurusRex** [comment]
Cutter tool at the ends of the line, select line, drag thickness to 0?

**Comment by ladlon** [comment]
Hi, RattusaurusRex...  Ya, that's one of the ways I was thinking.  Certainly would give you the most accurately/closely placed border lines.

I seem to be having trouble getting zero width lines, though.  With the pump tool, it seems like it stops before zero.  I don't recall if the global (Select Tool) width adjustment had the same issue.  I'll try again.

I thought for a moment that colour guides(?) might work, but those appear to only be for within a filled area, and still require an overall border around the shape.

Currently, I'm using a separate line (manually drawn) that has the same colour as the fill.  It works, but any nudge in the geometry usually ends up with a fill break, and you got to drag the ends back to the newly moved wall.

I was previously also thinking I might be able to draw an invisible line with the index0 colour... or a custom colour set to 0 alpha.

Too bad there weren't dedicated no-render lines that you could just very loosly draw across a shape (without worry of matching the ends to the wall of the shape) that would prevent the fill from spilling out the open end.

I got to play around more with zero width lines.  So far, I've been mostly trying it via the Pump tool, but it seems that doesn't work (it still renders a surprisingly thick line, different from that of the non-preview/render mode viewport display).

I'm currently battling the whole trouble with having a lower arm cleanly attaching to an upper arm, so that it doesn't look stupid when you rotate the lower arm.  I saw an interesting vid showing a fix to that by using two copies of the lower arm (one with the outline, and one without, which goes on top of that)... and clever use of the MatteIn and MatteOut nodes.

**Comment by artisteacher** [comment]
You could also create a 2nd rectangle on top of the first with the same fill without a border. It would just need to be large enough to cover the top edge.

> I saw an interesting vid showing a fix

Sounds like the sandwich method. There are several ways you can use FX to accomplish this. There are actually several examples if you [search the Google Group](https://groups.google.com/forum/?oldui=1#!searchin/opentoonz_en/sandwich%7Csort:date) for OT. There are even some macro FX that were shared that you might want to try out.

**Comment by ladlon** [comment]
Yup... a few ways to do this... although many (all?) are vulnerable to edits, which often break the seal holding the fill in.

I suppose you can group the object and the separate wall together, although that only would protect against a global distortion (Select tool), and not a Control Point edit.

Ideally, you should be able to change the line thickness of individual lines between two control points (rather than trying to guess the appropriat brush size to cover the line's length, and not overshoot the control points).... or, have a feature where you can click on and 'hide' individual line segments (something Moho has, actually).

The current system works... but the 'live' fill makes for a bit of extra work and/or frustration when it gets broken during a control point edit (as the result of the line having to be separate from the main object, in order to do the 'hidden' line state).

**Comment by ladlon** [comment]
@artisteacher: Ya, the 'sandwich' method.  I have to look into it further.  It is a good method, although needs a bit of setup.  For my particular project, I actually managed to bypass the need by having my character's elbows conveniently behind the large armrests of the chair he's in!

**Comment by jeremybullock** [comment]
This question would be better to be asked on the new Google group or in the Tahoma2D discord.
https://groups.google.com/g/tahoma2d
https://discord.gg/4HUXF6F

In the interest of clearing up the issue list here on GitHub, I'll be recommending this on a number of questions in the issues.
