### ISSUE TITLE
Crash on selecting "Vector" tab above the Color box (2D room / workspace)

### ISSUE THREAD

**Issue by tushantin** [turtletooth/tahoma2d#284]
I couldn't seem to find an existing bug, but in case it's already been submitted, please deleted this. 

Tahoma crashes every time you select the "Vector" tab on the top-left box. Doesn't matter if you're on the Camera layer, Smart Raster or Vector layer. 

Also, does this occur with OpenToonz too, or should I test this separately with that and file a bug-report there too? Or will the fix be transferred upstream if it occurs with that too? 

**To Reproduce**
List steps to reproduce the behavior.
1. Stay in the 2D workspace / room. 
2. On the top left Color box, which has the color-wheel on it, find the "Vector" tab. 
3. Click on the "Vector" tab. 

**Expected behavior**
Boom! Crash. 

**Device Information:**
 - OS: Ubuntu 20.04.1 LTS
 - Tahoma Version: 1.0.1
 - GPU: NVIDIA GTX 750 Ti
 - GPU Driver Version: 450

**Comment by artisteacher** [comment]
This is an issue on OT too:
https://github.com/opentoonz/opentoonz/issues/3214
