### ISSUE TITLE
Migrate preferences and layouts from prior Tahoma2D version

### ISSUE THREAD

**Issue by manongjohn** [turtletooth/tahoma2d#286]
Right now the only way to upgrade Tahoma2D and keep any preferences and layouts is to replace the contents of the existing Tahoma2D folder with the contents of the new Tahoma2D folder, replacing everything that is in conflict.

Add an `Import Preferences and Settings` option which will
1. Prompt for the location of an existing `tahomastuff` folder (allow OT stuff & portablestuff folders?)
2. Provide the ability to selectively import: profiles (personal preferences, layouts), sandbox, projects, studio palettes
         Note: some personal stuff is stored in the `config` folder such as custom brushes. (side note: should move these to personal settings folder)

**Comment by artisteacher** [comment]
Yes please!

**Comment by jeremybullock** [comment]
I dig this.  That would be sweet.

**Comment by DarrenTAnims** [comment]
I like the sound of this. But one issue to remember, is that if there's a new command added to a menu and you copy your menu layouts, then you won't have the new menu command. The same goes for rooms. If a room in the new Tahoma has a new panel in it, copying your old rooms, won't show the new layout or new panels.

**Comment by artisteacher** [comment]
Would this be similar to the approach in OTX?

The difficulty on the macOS end, is that the stuff folder is inside the app itself. So updating to the newest release means the old one is likely in the trash.

**Comment by manongjohn** [comment]
@DarrenTAnims That is why it is optional. Users will need to understand doing that may hide new changes.  Not much I can do about that. It's similar to OTX. Same would happen in OT when upgrading the existing installation.

@artisteacher Yes , it will be similar to OTX.  In a way, it would be the same issue for Windows and Linux depending on how a person choses to upgrade.

When upgrading, instead of trashing the prior version right away, I would suggest renaming the old version/folder then unpack the new version.

**Comment by jeremybullock** [comment]
This has been done.  Thanks @manongjohn
