### ISSUE TITLE
Rotate drawings along X/Y axis?

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#296]
Good day...  I just wanted to verify...  Currently, it doesn't appear that Tahoma2D has the ability to rotate images/levels along the X or Y axis, right?

Specifically, I was wondering if I'm able to create a ground/floor with a level/drawing that is actually oriented 'lying on the floor' (with it's 'normal', to put it in 3D terms, pointing upwards).

The scene I'm working on has a character sitting in a chair, and I want to put him within a multiplane scene, but am not sure how to best address the floor, since a 2D floor (as a flat, facing camera drawing of a floor, drawn in perspective), will conflict with any camera movement, since the perspective will not change... and you have the issue of how to deal with it not drifting relative to the characters foot/chair leg contact points on the floor, while still allowing the 'distant section of the floor' to move in parallax.

Currently, without having the ability to do a floor drawing that is actually laying on the ground, I can only see addressing this issue with either a series of floor drawings, separated into various distances (kind of like planks, which move independent of each other, allowing a sort of parallax effect)... or just making the floor have no distinguishing markings that hilight any drift between the character and the floor area they are on.   (Well, that, or just crop the shot at the ankle!)

So, I just wanted to see if Tahoma is strictly a 'drawing facing camera' multiplane kind of thing.  Never know if there is some hidden feature I might be missing!

**Comment by RodneyBaker** [comment]
Toonz and it's various flavors doesn't have an actual 3D space so everything that approximates that is tricks and hacks.
One could argue that pretty much all 3D spaces in a computer are tricks and hacks though...

The primary way we get at '3d space' in Opentoonz is through fielding which then allows various adjustments to appear as if they are moving in 3D space.

Yes, the  primary approach is very much that of the multiplane camera.

![image](https://user-images.githubusercontent.com/2576432/95385888-30281200-08b4-11eb-83eb-917f5072ba91.png)

In this image we can see the field indicated but something often overlooked is the option to the right of that (in brackets).
If that value is set to be the same as the field then the image will remain the same size with respect to the camera even though it is set to be at a different field size.

There isn't a lot of documentation on this one we could probably do quite a bit to lean toward a pseudo 3D environment but in the end it might be better to simply use other applications in conjunction with Opentoonz to gain the 3d space.  The two primary application that come to mind being Fusion (standalone or via Davinci Resolve) and Blender.

Note that to 'rotate' images in psuedo 3d space we likely would use Shear (via Animate Tool).

![image](https://user-images.githubusercontent.com/2576432/95386670-42568000-08b5-11eb-8dff-d34f73c771b6.png)

**Comment by RodneyBaker** [comment]
![image](https://user-images.githubusercontent.com/2576432/95386989-bee95e80-08b5-11eb-80f2-dd521f94de75.png)

**Comment by ladlon** [comment]
Ya, I figured that the software was really just a multiplane 'world', but not a fully 3D one... and I imagine adding a 3D environment might be a huge undertaking, and maybe even mess up the current system somehow.

As much as a 3D environment would be great, I'd even be happy with a perspective hack, done via a 4 point distortion, but done automatically by the software, rather than the user having to figure out the settings and animate them appropriately.

In my current project, it would just be for a floor, which I'd like to properly 'receed' into the background and move with the proper (internal) parallax.  I suppose that MAYBE (if the current features allow it), I could link the x value of the camera position to some sort of skew or top left and top right corner of some 4 point distortion node... perhaps?).

Failing that, I go really old school, and horizontally slice the floor, and nudge each slice further into the background for some multiplaning.

Ah, well.. Maybe farther into the future, a 3D environment might be added.

**Comment by RodneyBaker** [comment]
There is much we can do short of full 3D and not only the standard we have had in Opentoonz but also what has just come online with stopmotion and camera/webcam support.

I figure if Hollywood types can fake entire environments on a set then we can probably come pretty close to that as well.

Don't be afraid to think big here...
Tahoma2D has gained not only fuller camera support but now also has UI transparency where we can look through the canvas onto anything we have set behind the application.

The webcam support also suggests how we might pull 3D objects from either other screens or from the real world into Opentoonz.

We can certainly wait for the future... but while we do we can also build it. :)

**Comment by ladlon** [comment]
For sure... I'm just respecting the fact that this is free, and doesn't have a gigantic team behind it.... plus I'm trying not to sound like I'm insisting on a giant list of potentially difficult/impossible features, and am not appreciating the great work done up to this point.

But, ya, I imagine some sort of 'cheat' could be added sometime soon... even if just for the sole purpose of creating a ground layer.

I'm very eager to see what new things show up in future versions.  I'm coming from Moho, and am actually in the process of working on my very first (real/broadcast) OT/Tahoma2D project.  So far, so good... although my knack for running into obscure software bugs seems to still be as strong as ever.
