### ISSUE TITLE
Question: Change timeline/xsheet insert command

### ISSUE THREAD

**Issue by jeremybullock** [turtletooth/tahoma2d#306]
Right now the insert command on the timeline/xsheet inserts below the current column/layer.  The insert above command is shift + insert.  

The current behavior does what people generally expect from an insert, but is this a different case?  When a user hits insert in the timeline, do they usually want a new column above the current column or below?  

I get that the current behavior is in keeping with insert elsewhere, I was just wondering if making it a one key solution for a user to get a new layer/column is worth considering.

**Comment by artisteacher** [comment]
It doesn't make a difference to me  - I always forget insert is a thing since there's not an insert key on my keyboard.
