### ISSUE TITLE
'Bug Report' label doesn't always get applied....  Probably me...

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#316]
Hi.  I've posted a number of bug reports here, but sometimes the Bug Report label doesn't get applied, even in cases where 'Issue:Bug Report' was clearly displayed above the title while I was typing it. 

I am fairly sure I clicked the Bug Report button EVERY time... certainly on the one I just posted now, yet sometimes the post lacks the intended label.

Anything I need to watch for on that?  And, is there any way to add the label AFTER the post has been made?

UPDATE: Okay, I just posted this, and it TOO doesn't have the label... So, something appears to be wrong here...

**Comment by artisteacher** [comment]
I think that Jeremy assigns the bug label manually, once he determines that an issue is truly a bug.

**Comment by jeremybullock** [comment]
i don't mind things getting automatically labeled a bug. i think i just fixed it.

**Comment by ladlon** [comment]
Okay, cool... I just thought I was doing something wrong.  It definitely said Bug Report at the top on the last two, but the actual published post lacked the label.  Kind of random.  I'll let you know if I have it happen again.
