### ISSUE TITLE
Window dividers sometimes do not trigger 'window resize' mouse pointer

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#318]
I haven't seen any particular trigger for this, and sometimes it happens immediately after launch...

Sometimes the divider lines between windows/palettes that you normally grab/drag to resize the windows do not trigger the 'resize window' mouse pointer, and do not allow resizing of windows.

Just seems random.  If I can find any kind of correlation to it and some action, I'll post it... but so far, nothing.  Just randomly happens.

Win7Pro

**Comment by manongjohn** [comment]
This normally happens for me on the Level Strip or Palette panels, both of which were coded to not resize on initial startup.

Though the mouse cursor never switched, I would still be able to grab it and resize it if I was in the right place. Usually once I am able to resize it, the mouse cursor would change normally  when over the divider.

**Comment by manongjohn** [comment]
Btw, is this the same as #317?

**Comment by ladlon** [comment]
In my case, it's often the divider between the timeline and all the other windows above it.... although often when it happens, I try and grab every divider (horizontal and vertical), just to see if it's a specific divider (...and so far, it's always been all of them, I think).

**Comment by ladlon** [comment]
Huh... I double post.  The first time I tried posting it, I got a 404 error.  Looks like it managed to save it.  I will try and delete it.

**Comment by ladlon** [comment]
The divider issue is happening to me right now, and actually only the horizontal divider between the timeline and the other windows (which are all above the timeline) is not functioning (no mouse pointer change, and no ability to rezied).  But, the vertical dividers of the windows above it are working.

**Comment by jeremybullock** [comment]
what version are you running?

**Comment by artisteacher** [comment]
I've been running into this issue at school. I'll try updating to the latest version tomorrow & see if it makes a difference.

**Comment by jeremybullock** [comment]
i think my tweak to the timeline height is causing this. it has been reverted, and hopefully 1.1 won't have this issue.

**Comment by jeremybullock** [comment]
if you want to try the latest version with the (hopeful) fix, you cantest it here.
https://github.com/turtletooth/tahoma2d/releases/tag/v1.1-alpha.2

**Comment by ladlon** [comment]
I'm running Tahoma 1.0.1 Sept 3 2020.

Is there a later version?  (That's one thing I've been curious about.  I can't seem to find anything on the site that indicates the version of the available download.. and the software doesn't alert you if there's a new version, or have a feature to check if a new vesion is available.  Am I missing some other download page?  I go to the main page of the site, and there's just the 'download' button, and only offers one (unmarked) version.

**Comment by manongjohn** [comment]
Current releases, pre-releases and prior versions can be found here https://github.com/turtletooth/tahoma2d/releases

**Comment by ladlon** [comment]
Neat... Is that accessable through the regular website?  I just find that one download button on the regular site page.

Hrmm.. Looks like I'm up to date, as far as full resleases are concerned.

I'm wondering if I should update to the alpha... I'm literally working on a broadcast project, so I don't want to risk any weirdness.  The alpha may fix some issues, but may introduce others... so, I'm not sure what the wise thing to do is.

Are projects done with the alpha versions (1.1) loadable in the current full release (1.0.1)?  If not, I better stay with 1.0.1.

**Comment by manongjohn** [comment]
Well, the nice thing about these being portables, you can keep both :)  Either rename the main folder of one of them if you intend on keeping them in the same spot (i.e Program Files) or keep them in 2 different directories.  Only problem is you will need to re-setup your preferences and layouts in the new version .

You should have no problems opening projects created in 1.0.1 with 1.1.  There aren't any particular changes that would affect how scenes are stored/saved so you should be able to open existing projects with either version.

Hopefully you are making your projects outside the `tahomastuff` folder so they can be easily accessed by any version you have and won't have to worry about stuff getting deleted or lost during an upgrade.

**Comment by ladlon** [comment]
No, what I'm worried about is loading 1.1 files in 1.0.1... in case there's something funky happening in 1.1 (alpha).

**Comment by manongjohn** [comment]
You should be ok since I can't think of anything that would have altered how things are being saved to level or scene files. That is the only reason something might not be forward compatible. 

As usual, backup before doing anything just in case!

Wholly understandable if you are concerned. I would recommend only use the new version with new projects/scenes or once you've fully committed to upgrading and not going back. I don't usually recommend upgrading in the middle of a project for that reason.

**Comment by ladlon** [comment]
Ya, I'm probably going to stick with 1.01 for this project.  I'm already pushing my luck, as I'm doing a broadcast project with software I now only have about a week of experience in!

Up to now, I was using Moho12Pro, but always wanted to make a switchover to OT... and so I decided (for better or worse) to use this latest animation project as a means to give OT (and myself!) a proper test run.  So, I taught myself over the last couple of days.  But literally a few days after starting, I discovered Tahoma2D, and switched over to that (due to some of the very nice UI changes, etc... as well as the seemingly very responsive and very promising team working on it).  So, I literally just had a couple of days in OT itself.

It's all going well, although (as is unfortunately the case) I seem to be really good at discovering bugs (...I would be a great playtester, it seems....).

The only thing that is giving me somewhat worrisome grief is the maximizing / bottom edge stretching way out beyond the bottom of the monitor bug I discovered.  I can currently get by (for the most part) by working in Restore Down window mode (as opposed to Maximized)... but even then, things are a bit weird.  Sometimes I can't scroll the timeline up... and very often, I couldn't make the (currently quite tall) timeline window a bit smaller, so it's not hogging over half the screen space.

...and, then there's the weird thing where some levels are rendering in front of where they should be in the stacking order... despite everything in the Schematic seeming to be correct.  The regular view mode shows everything fine, but the 'rendered' view mode is showing one level being far ahead in the stacking order than it should be... and I'm not sure why.  Even weirder thing is, it was rendering fine before.  I only added a new level, and now things are kind of messed up.  I posted a question about it here, so hopefully someone can steer me in the right direction.  Otherwise, I might be in trouble, if it doesn't 'allow' me to add any more levels.

As long as things don't get worse, I can work around this, I think.  Just a little awkward and 'inconvenient'.

I'm loving the results I can get.

**Comment by artisteacher** [comment]
Still an issue - at least for the Style Editor panel. Timeline seems fine so far on Alpha 2.

**Comment by ladlon** [comment]
Ya, for me it's usually the divider between the timeline (which occupies the entire span of the bottom section of the screen) and the rest of the windows above it.  Seemingly random, although I thought at one point it might be based on if the entire Tahoma2D window is in Maximized or Restore Down mode... but I'm not sure.

I think in my case, too, I'm currently battling with the bottom of the entire window extending off the bottom of the monitor edge... and that may be causing/affecting part of it (in how the timeline area itself is reacting to the resize pull... as the bottom of the monitor may no longer be acting as a well, so the timeline is just MOVING DOWN, rather than being squashed against the bottom edge... I think.  Really hard to say.  Kind of broken over here at the moment, due to that Maximize bug thing, I think.

**Comment by jeremybullock** [comment]
This all should be fixed now.  The timeline one should have been fixed in 1.1, and I'm pretty sure I fixed the vertical dividers today.
