### ISSUE TITLE
Keyboard Shortcut for "Set Start Marker" / "Set End Marker"

### ISSUE THREAD

**Issue by Mainman002** [turtletooth/tahoma2d#321]
In other software for video editing you can set a keyboard shortcut for In / Out loop points on the timeline, so far I can't seem to find the proper term / feature to set these to keyboard shortcuts from within Tahoma.

Being able to find / set "Set Start Marker" / "Set End Marker" in the keyboard shortcuts settings menu. This would allow me to setup my graphics tablet / external control buttons for faster timeline editing between a loop area, as I'd be able to expand / shrink the zones with a fast button press vs a few mouse clicks.

![image](https://user-images.githubusercontent.com/11281480/95466252-c35b5900-0941-11eb-82c5-f62afdcf05f0.png)

![image](https://user-images.githubusercontent.com/11281480/95466310-d40bcf00-0941-11eb-9f08-c494444adc6d.png)

![image](https://user-images.githubusercontent.com/11281480/95466343-e0902780-0941-11eb-8bfc-5f5811480ec8.png)

![image](https://user-images.githubusercontent.com/11281480/95466460-fa316f00-0941-11eb-8b0e-6298730b39cd.png)

**Comment by beeheemooth** [comment]
I had the same feature request, only I suggested that it go like this:
![ezgif-3-8dc342aa709e](https://user-images.githubusercontent.com/25724133/95500578-a6f60580-09af-11eb-816c-463a755f4bf9.gif)
Shift + CLick on the strip of frame numbers selects all current frames in all (unlocked) columns (This is in the program at the moment)
Ctrl + Click - Set Start Marker
Alt + Click - Set Stop Marker

**Comment by jeremybullock** [comment]
#324 Will take care of this.
