### ISSUE TITLE
Camera Capture crash on open

### ISSUE THREAD

**Issue by artisteacher** [turtletooth/tahoma2d#322]
**Describe the bug**
Immediate crash on opening the camera capture window.

Do we still need camera capture since we have the stop motion controls working for all supported OS?

**Screenshots**
![Screen Shot 2020-10-08 at 1 38 28 PM](https://user-images.githubusercontent.com/21159116/95494431-e864c180-096b-11eb-9c6c-0b4baff4e4e5.png)

**Device Information:**
 - OS: macOS 10.14.6 & 10.15.6
 - Tahoma2D Version: Alpha 2

**Comment by jeremybullock** [comment]
I'm not sure what the best thing is to do with camera capture.  It has a few features that aren't in stop motion.

**Comment by jeremybullock** [comment]
(yet?)

**Comment by artisteacher** [comment]
There's definitely some features there that would be great in the stop motion controller. Maybe something for 1.2?

It might be better to remove it sooner rather than later, so people don't get too tied to the work flow. Unless you want to keep it as an alternative of course. I also think it might be confusing when Canons work on one but not the other.

**Comment by artisteacher** [comment]
It sounds like there's a crash on Linux too. 
[https://github.com/turtletooth/tahoma2d/issues/147#issuecomment-711109425](https://github.com/turtletooth/tahoma2d/issues/147#issuecomment-711109425)

**Comment by jeremybullock** [comment]
Fixed in #378
