### ISSUE TITLE
Undocking Scene Viewer doesn't cause Palette and Style Editor to expand Horiztonally

### ISSUE THREAD

**Issue by manongjohn** [turtletooth/tahoma2d#325]
**Describe the bug**
Normally when undocking things adjacent panels surrounding it will resize to fill the space. Normally if no adjacent panel can be resized, the panel cannot be undocked.

In the 2D room, you can undock the Scene Viewer but the Palette and Style Editor doesn't expand horizontally like it's supposed to, leaving a hole in the layout.

When this happens, you cannot undock anything else and if you try to resize anything vertically, Tahoma2D crashes.

NOTE: This happens in OT also

**To Reproduce**
1. Open Tahoma2D to 2D room
2. Unlock the panels
3. Undock the Scene Viewer   -> Palette and Style Editor do not expand to fill the space and it should
4. Try to undock something else. -> You can't
5. Try to raise/lower the timeline -> Crash

**Screenshots**
![image](https://user-images.githubusercontent.com/19245851/95536535-3c49c780-09b9-11eb-8eb1-5690fe88205f.png)

**Comment by jeremybullock** [comment]
Do you have any thoughts on this one?  Panel management has been something we've wrestled with for a long time.
