### ISSUE TITLE
Vertex colouring

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#329]
A feature of Moho that I'd love to see in Tahoma2D is vertex colouring.

Basically, it stores a colour into each vertex (control point) of a shape, and creates a live colour gradient between each one, allowing for a dynamic, custom set of multiple gradients within a shape... great for creating colour variations over the surface, or shading/faux lighting, etc... and the gradient is live, so it moves/distorts with the shape.

Here's a video showing the feature in Moho:
https://www.youtube.com/watch?v=vlciKhlOmsc

**Comment by jeremybullock** [comment]
This would be awesome.  But unfortunately, it's not doable with the way vectors currently work in the software.  Blender does have this though.
