### ISSUE TITLE
Bone dynamics

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#330]
Another nice Moho feature I'd love to see added sometime to Tahoma2D is bone dynamics.

When toggled in the bone attributes, it adds physics to the bone, giving it inertia, so that movement of the parent bone (or object in general) causes interia-based movement (sway, jiggle, bend, etc).  Awesome for effortless secondary animation.

You have a set of attributes which controls the behavior (like it's stiffness, etc).  Great for things like 'bunny ears', hair, belly jiggle, dangling things, etc.

Here's some vids illustrating the feature in Moho.  Hopefully, this is something that can be added to Tahoma2D in time.  I think it would be very valuable!

https://www.youtube.com/watch?v=21-eHoP2oWk

https://www.youtube.com/watch?v=Xw9PJExn95U

https://www.youtube.com/watch?v=p0oUWdH7wnU

**Comment by jeremybullock** [comment]
This would be really cool, but is currently beyond the scope of what I think we will be able to offer.
