### ISSUE TITLE
Still struggling with timeline editing

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#335]
One thing that I am struggling with in Tahoma2D is editing a timeline that has existing keys.

I think maybe it's even safe to say I'm finding editing the timeline in general, in Tahoma2D, challenging (...due to my expectations, from using other software for many years).

I'm hoping (and suspecting) that it may just me not being aware of some keyboard shortcuts, or features... or something.  But, I'm really finding things a bit clumsy and requiring cleanup after each action.

It's a bit hard to put it concisely, but let me give it a try:

1) If I have (say) a 90 frame animation, and I'm animating the lipsync of the mouth column, I typically have the timeline column filled with the first mouth position (usually neutral) spanning the entire 90 frames (so his mouth doesn't disappear part way through the animation as I preview).  I move to the first frame where I want a mouth change, use my hotkeys to cycle through the different mouth drawings until I get to the one I want.  But, in doing that, Tahoma2D only changes that one frame, and adds an additional keyframe after that, to return it to the previous mouth position.  I get why... It assumes I want to only change the on (current) frame... but that's not what I want to do.  Is there not a way for me to add that 2nd mouth key, but have Tahoma2D have that span across all the frames after it?

2) The same sort of thing happens when I am changing an existing mouth key which is in between existing mouth keys.  The only way around it appears to be to select all the frames within the existing key event, but that can get tedious having to do that for every edit.

3) I seem to be completely perplexed about editing keys for a Plastic tool mesh.  How do you copy/paste values from one key in the other in the timeline?  The expected way (literally copy and paste) doesn't appear to work.  I keep trying to do a hold between two sections of action (by just having the same value between the last key of the first section, and the first key of the second), but I keep getting drift, regardless.  (BTW, I'm talking about doing this in the timeline, not using the spreadsheet)

4) Overall, I'm finding most times I have to continually just select and erase the 'tail end of the timeline, after my current keyframe, just to clean up and/or restore the intended structure.  Seems like I'm missing some key editing commands/features.

I just seem to be really struggling sometimes between how I anticipate something will work vs how (seemingly) it does actually work.

Are there any good tutorials thoroughly going through these types of edits?  All the vids I find are very basic, and most of the time, they are simpy creating the animation linearly (one part after another), without any backtracking or editing.

**Comment by artisteacher** [comment]
1. Click and drag to select the range of frames for the next mouth drawing before using W/Q

3. Make sure to click on the keyframe in the Timeline so that it turns blue. Then you can copy the keyframe. Move to a different cell & paste should work as expected. 

If you are trying to create a hold, you can also set the first keyframe by moving the plastic skeleton. Then go to the frame where the hold ends and click on the keyframe icon icon in the bottom of the viewer. Obviously that would only work if there's not a keyframe later on.

**Comment by ladlon** [comment]
Re:1+2: Understood, but I wish there was a more streamlined way to do that... Like doubleclicking on the keyframe to select the span.  I'm finding that Tahoma2D currently seems to have some unnecessary busywork for some actions, and the fact that those actions will be happening quite often kind of multiplies the issue.  It reminds me a bit of animation software that has some actions done via a pulldown menu... Seems harmless at first, but then if you are doing it thousands of times over the course of several hours, the tediousness of it becomes very apparent.

Re:3: I try it some more.  I found it seems VERY finicky, and often hard to select... but that is remedied by zooming in on the timeline (...which, again, is more busywork, but at least it's a workaround).  I discovered the CTRL+Drag method of copying mesh keyframes... but again, it can be REALLY finicky (unless you zoom in).. and it doesn't let you drag onto an existing keyframe, so it's only good for new keys.

I'm finding, too, that some of the documented features (including in vids) are not matching the current version of Tahoma2D.  Things like Shift dragging a selection of cells to move them (...I have to use CTRL).

I'm often frustrated by it not allowing me to simply shift an existing Drawing Number key over, without disturbing the rest of the keys (....again, unless there's some existing feature I'm not aware of).  For whatever reason, I'm just finding that simple actions I want to do don't SEEM to work.

Again, I really wish there was a current, complete video on ALL editing aspects... rather than just ones of people animating raster ball bounces in a linear (no keys/content after it) way.  It's very easy and straightforward when you are animating like THAT... with no other content, and you are just adding frames in a linear fashion.  I'm concerned more about moving/shifting/copying things around in a complex, already occupied timeline.

**Comment by ladlon** [comment]
Another example...

I hilighted a keyframe, hit CTRL+C, moved to another area of the timeline (same column, no key on that frame), and hit CTRL+V.

A key is created, but it nudges the whole timeline after it over, throwing my timeline out of sync.

Now, I have to cut out one frame, and nudge it back... every time I do a paste (....again, unless there's some feature I'm not aware of).

I'd think the paste should paste OVER the frame, not insert a new one (by default).  I can't think of many instances where you'd want it to shift the existing timeline over during a paste.

**Comment by artisteacher** [comment]
> I'd think the paste should paste OVER the frame, not insert a new one (by default). I can't think of many instances where you'd want it to shift the existing timeline over during a paste.

The shift only happens when pasting between 2 keyframes but I completely agree - I don't see why there should be a shift at all.

>  Like doubleclicking on the keyframe to select the span

Something like this would be fantastic.

**Comment by ladlon** [comment]
Yup...

But, that's what I'm talking about with all the unnecessary busywork... often cleanup for some action (...like deleting a key and shifting the entire timeline over to resync the offset it creates, for no reason).

I'm currently having a fierce battle with the graph editor.  I seriously don't understand the logic of it.  Not that I don't understand graph editors... I've been using them since 1990!  I'm talking about how Tahoma2D works in their graph editor.

I'm getting furious every time I want to edit a particular channel, and the editor shows me about 20 graphs, most of channels/columns I have no interest in.  Why is it displaying these random channels?  It's impossible to spot your target graph, because they all look the same (the selected one is not thicker or anything), many share the same colour, etc.  I would have thought that simply clicking on the channel in the channel list on the left would do it, but it doesn't seem to do anything other than make the text yellow (...which is seems to be doing to random channels in the list anyway!).

Beyond not knowing why all these random channels are being displayed by default (and forcing me to manually expand and click on every one of them on the list to somehow try and deactivate their display in the graph), I can't understand why there isn't a simple 'Display Selected' option, and you just click (highlight) whatever you want on the list.  Add to that a 'Display All' and Display None' button, and you have everything you need... assuming the graph editor launches with a clear graph/selection.

Opening the graph editor should open completely clear, and you then just click on whatever you want, or click Show All, if you want a full overview.  If you have a lot of channels currently shown, and want to view a single one, you just hit Show None.

I had to redo my channels that were driven by the values of another column several times in a row, because it seemed to keep erasing my expressions and setting them to ease in/out interpolation (removing all my keys).  And I had a heck of a time actually setting it so it would actually allow me to even define an expression, as you have to set some keys in the channel, otherwise it won't allow access to the expression field... and in order to set keys, I had to actually select the channel... which it also seemed to fight me on.

Grrrrr...   I am not a fan of the current Graph editor.

(Speaking of which, is there no way to have it apply a different default value for eas in/out?  I have it set as the default interpolation, but it's no better than having the default as Linear, as the VALUES themselves create no curved slopes/ease... so I have to go in, one by one, and manually adjust the ease slopes... defeating the whole purpose of a default.  Plus, I have to make sure I don't forget to adjust any, after adding more keys each time....)

**Comment by artisteacher** [comment]
There is a "display all" and a "display animated only". I so agree that there needs to be a "display selected" option.

> is there no way to have it apply a different default value for eas in/out?

Not that I'm aware of.

**Comment by ladlon** [comment]
I just made a big discover (...had my AHA! moment) while experimenting and writing a post in your Improving The Manual thread.

I suddenly realized why there was a seemingly HUGE conflct between what the manual was saying (relating specifically do drag operations of cells in a timeline) vs what I was seeing happen.  No bugs or anything... It was a misunderstanding on my part.  Some of the drag operations outlined in the manual only work when dragging to an unoccupied cell area... and others are visually a bit hard to see the effect of while doing them.

So, with that new understanding, I am going to do a session where I'm just trying various timeline editing tasks, and making sure things now work the way I expect, and then really try to drill that into my head so it becomes second nature (as far as muscle memory of the shortcuts and procedures).

The graph editor is still a thing of pure evil, though...  ;)

**Comment by DoctorRyan** [comment]
You mention there is no video documentations on timeline editing complex
scenes.  I am planning on doing a reboot on my Youtube Channel with
Tahoma2d as topics I wish to discuss.  I am curious what your overall test
enviroment would be on tutorial wise?  Im not the best artist in the world
but I do know about the Toonz way of working things.

**Comment by ladlon** [comment]
Hi, DoctorRyan.  Ya, I'm finding many of the tutorials start from the very basics, but usually stop there, before getting into more complex or 'mid-project' kind of modes.  Often, they show hand-drawn projects, where they are drawing something on the first frame, then moving forward and creating a new drawing (which automatically gets placed after the first drawing on the xsheet/timeline, and so on... Very linear.

Some do show how to select and move groups of cells within a level/column, and sometimes even to other levels/columns... yet, most of the time, it's always in a project where there is only a few cells occupied (a very sparse 'just starting' kind of project state).

Where I still fumble around currently (although some recent 'Aha! moments' may have improved that recently), is in doing things like:

-Selecting a group of cells (in a project that has a long stretch of occupied cells, filled with keyframes), copying them, and then pasting them overtop of a section of occupied cells (replacing the existing content, and not shifting the cells afterwards).  I think I got that working now, although I believe it may still shift the cells.

-Moving a 'drawing' keyframe (not a translational) up/down the timeline without disturbing any of the surrounding content (...basically a 'slide' edit).  Sometimes, I'll have a large block of keyframed cells, some with more than one frame exposures, and want to grab one of the keys (that has hold frames on either side) and simply slide it forward or back in the timeline... but without disturbing the surrounding area (and without creating a gap, which then has to be filled in again).

It's hard to list/describe them, other than to say the current system seems confusing, and possibly inconsistent.  Certainly not intuitive, at least to me and my expectations based on other software.  It seems tricky memorizing the existing keyboard shortcuts/techniques for moving/copying/sliding things around... almost like there's no relation between them.

Some of these I have figured out, whereas some might still be a bit of a mystery.  I'm listing ALL of them, just for completeness sake.

The actions I'd be interested in are:

-Select cells, copy and paste (shifting cells afterwards)
-Select cells, copy and paste overtop a section without shifting cells afterwards (a replacement edit)

-Select cells, cut and paste (shifting cells afterwards, and keeping the gap from the cut open)
-Select cells, cut and paste without shifting cells afterwards (a replacement edit), keeping the gap from the cut open

-Select cells, cut and paste (shifting cells afterwards, and keeping closing the gap from the cut)
-Select cells, cut and paste without shifting cells afterwards (a replacement edit), closing the gap from the cut

-Select keyframes and slide earlier/later along a second of held frames, copying over its destination, without disturbing any of the other keys (aside from any that are copied over
-Select keyframes and drag them earlier, pulling all keys AND cells with it (so all other key durations are unaffected)
-Select keyframes and drag them later, pushing all keys and cells with it (so all other key durations are unaffected)


Note that this is for both translational and drawing keys, as well as for destinations that are occupied and unoccupied (...as currently some things work only for certain situations, and not globally).

I hope this makes sense.  Again, some of them I know how to do, but overall, I find the current editing system seems to lack a common, global control scheme, and some actions seem to require cleanup afterwards (ex. extra frame is added, which needs to then be deleted to resync the timeline... or empty gaps are created that require manual refilling, etc).

And, again, one of the key factors being that this would be within the context of a mid-way done (or completed) animation, where the timelines are long, and filled with lots of drawing/translational keys that need to stay in sync relative to each other as you are making all these different edits (...as opposed to the usual tutorial scenario, where there's usually little or no occupied/keyed cells after the edit area).

**Comment by jeremybullock** [comment]
This question would be better to be asked on the new Google group or in the Tahoma2D discord.
https://groups.google.com/g/tahoma2d
https://discord.gg/4HUXF6F

In the interest of clearing up the issue list here on GitHub, I'll be recommending this on a number of questions in the issues.
