### ISSUE TITLE
Having problem on launching

### ISSUE THREAD

**Issue by kingK05Mos** [turtletooth/tahoma2d#340]
I'm using the appimage on linux mint. I added the shortcut on my menu but when launching it from there an error pos up. It's launching normely if I Double click on the Appimage file but I want it to launc from the menu for daily use.
![Screenshot_20201010_155754](https://user-images.githubusercontent.com/72651926/95652799-66160200-0b11-11eb-9763-f6cf5e333467.png) Though I'm not sure if it's a bug or what but an issue for me.
Thank U so much for making Tahoma and I wish you can help me with my problem

**Comment by manongjohn** [comment]
Is there a way to set the working directory to where Tahoma2d is on the shortcut?  When starting the AppImage, it uses the current working directory to find the tahomstuff folder.

**Comment by kingK05Mos** [comment]
Sorry I didn't understand. what do you mean by "working directory".

**Comment by manongjohn** [comment]
Nevermind. Currently it will not work through a shortcut on Linux. For now you will need to run it from the folder it is in.
