### ISSUE TITLE
Proper method of having shared character model in Tahoma2D

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#341]
Hello again.  So, I'm not sure what is the proper method for doing this in Tahoma...

If I have a rigged 2D character model that I built in Tahoma2D, and I am going to do several different scenes with them, what is the best means to have a master file that I can make mid-production changes to, and have it propogate to all the scenes?

Failing that, what method would allow me to manually load in altered pieces of a character into the multiple already-animated scenes?

I know Tahoma2D has the whole global palette thing covered, and that works great... But, I'm talking about the vector geometry/shapes.  I'm not really clear which way is best to deal with updating separate scenes with an altered version of the character (...ex. Changing his bowtie to a regular tie... or any actual geometric change).

Tahoma2D can only have one scene/project loaded, so I can't do a copy/paste.   And it seems you can only have one timeline, so I can't do all my scenes in one 'scene/project file'... or can I?

The 'drawings' library I create when making my vector levels are separately stored in the drawings folder... and they ARE shared between scene files, aren't they?  If I create a character in a scene file (Scene1a)... and then later, I create a NEW scene file (not a renamed save of the first scene file, using the Save Scene As... feature), is there some way for me to pull in the scene or models from the first one?  (I assume it will create a whole new set of folders for that project file)

**Comment by ladlon** [comment]
Okay, I may have just figured something out here...  It seems that any change to the drawings in ANY version of the scene file (previous versions, newer versions, etc) equally affect the library used by ALL the scene files... So, that's cool.

Still, I'm curious to hear what long-time Tahoma2D/OpenToonz users do as far as master files for characters they are going to use in multiple scenes/projects.

**Comment by ladlon** [comment]
As well, even though there's a system for sharing the palettes and for sharing the drawings, I'm not aware of how you can share/copy over/update things like the schematic, or the overall layout of the various levels (positions, rotation points, scale, etc).

I can see using a master file at the start, and creating the individual scene files from it... but once the scene is animated, I am not sure how you can copy over an alteration to (say) the heirarchy/skeleton, or position/scale of various levels (ex. body parts) of the characters.

(For example, if you need something specific...  Say you create a rigged character, then use that master file to create several individual scene files, which you then animate (a different animation in each scene).... and then you decide to alter the rotation point of (say) the elbow, and scale down the head (via a scale transform, not by adjusting the pictures... perhaps because there's a lot of them or something).  I know that any adjustments to the DRAWINGS will be updated/shared among the various scene files, but things like scale, position, rotation of the individual levels that make up the character, and rotation points and parenting changes (seemingly) don't have a means to propagate to the other scene files... and I can't even see how you'd even manually copy them over (aside from making the exact same changes to each individual scene file, which might be a bit tricky, if not just tedious).

If possible, could someone fill me in on how you'd address that sort of thing?

**Comment by jeremybullock** [comment]
The answer to your last part is to use sub-xsheets (now called sub-scenes in version 1.1).  These store the schematic and timeline of a scene.  
You can collapse a set of layers to a sub-scene and save that.  Then you can import that subscene into a new scene.  Any changes to a sub-scene will apply to all scenes using that sub-scene.  If you need to make a unique copy, you can save it as a new file or explode the levels back out into the main scene/timeline.

**Comment by ladlon** [comment]
Thanks for the answer.  I'll have to revisit sub-xsheets... I thought they were just a group of columns packed into a single column, like a folder, for xsheet decluttering.  I wasn't aware it stored schematics!  Awesome.

Cheers
