### ISSUE TITLE
Multiple redundant fills stored?

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#343]
I'm curious about something...  I see that sometimes a fill appears to be a 'live' process, where it appears/disappears as you adjust the shape.  So, that makes me wonder if the 'fill command' for lack of better name, is stored and constantly applying itself.

If that's the case, I then wonder if multiple versions of the fill are stored, in cases where you re-applied the fill multiple times due to the shape being changed and the fill(s) breaking.

If you fill a shape multiple times, is only the first one 'stored', or does the shape accumulate all the previous fill attempts?

If it does store them all, it seems that could be a trigger for issues, if all those fill attempts remain live, as they may suddenly 'succeed', and an unwanted/old fill gets triggered.

And, if that's the case, maybe there should be some feature to clean up redundant fills.

But, if it only stores the one fill... then all that is moot.  Just figured I'd ask, though.

**Comment by jeremybullock** [comment]
The way that vectors work in Tahoma2D is that lines are the only thing that actually exists.  The software then calculates regions in the shapes and those regions can be fillable.  It doesn't accumulate per region, but the region calculation can change as the shape changes.  It is buggy and prone to some interesting/frustrating behavior at times.

**Comment by ladlon** [comment]
Thanks for the answer.  I thought it stored the 'pour point'... and because it seemed live, I was concerned that all the previous attempts (which then became broken) would still be active.  Okay, cool.
