### ISSUE TITLE
Optimize shape command/tool?

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#344]
Title says it all.. Some means to remove redundant control points.

I thought for a moment that the Iron tool was doing that, but it appears to just straighten out the bezier handles, while maintaining the same number of control points.

The tool I'm suggesting would basically be doing the opposite of the Iron tool, where it reduces the number of control points, but TRIES to maintain the original shape.

**Comment by jeremybullock** [comment]
This is something that I am going to close for now in hopes of reviving it once the vector system is improved.
