### ISSUE TITLE
Remove need for glut32.dll

### ISSUE THREAD

**Issue by manongjohn** [turtletooth/tahoma2d#348]
A user on a Discord server downloaded and tried to start Tahoma and it complained it couldn't find glut32.dll. 

In  OT, the workaround is usually to copy the glut32.dll from the installation folder to C:\Windows\SysWOW64 and it fixes the problem.

However, the installation folder for Tahoma does not contain the glut32.dll. It has a glut64.dll.  We should probably be including glut32.dll with the installation.

**Comment by jeremybullock** [comment]
I'm not sure why it's looking for glut32.  Do you know why?   Everything is built for 64 bit, since we are no longer supporting QuickTime.

**Comment by manongjohn** [comment]
Actually, this may be, in part, a user error.  After I had him copy the glut32.dll from the OT folder to the SysWOW64 folder, he was having other dlls that couldn't be found.   Turns out he accidentally moved the Tahoma.exe out of the Tahoma folder when trying to make a shortcut on the desktop so it started throwing errors since it couldn't find them.  It's possible it is not needed.

That being said, I don't know why it was looking for a glut32.dll and not glut64.dll.

We can close it for now, if you want, and watch for an any issues that point to the missing glut32.dll and added it then.

**Comment by jeremybullock** [comment]
Looks like I didn't fully remove the mov stuff.  I'll take care of it.
