### ISSUE TITLE
Move Palette activation button out of title bar

### ISSUE THREAD

**Issue by manongjohn** [turtletooth/tahoma2d#351]
Since a docked Palette's title bar is hidden when the panes are locked, the palette activation button is inaccessible.

![image](https://user-images.githubusercontent.com/19245851/95917817-d1add880-0d78-11eb-894b-45a083020222.png)

I would suggest moving it to the bottom bar.  Also needs a tooltip to suggest what it is for and probably a status bar description for what it does.

Maybe something like this: 
Tooltip: Toggle Palette Switching
Status bar description: Allow (default) or prevent the palette from switching when changing levels.

**Comment by jeremybullock** [comment]
I left it there because it is so infrequently used, but you are correct.  It shouldn't be up there.
Does anyone actually use that?

**Comment by artisteacher** [comment]
I don't. Is it commonly used in studio settings?

**Comment by manongjohn** [comment]
I don't or havent needed to use it. Honestly didnt know what it was for or what it really did until I found what it was for in the OT documentation.

Apparently its used so you can have multiple level palettes open for different levels at the same time. This way you can easily compare/edit at the same time.

Is it particularly something that will be used often? Most likely not.
Will it probably confuse people? Yes 😁

Aside: There does seem to be a UI bug when the palette is inactive. Changing style in the Style Editor does not automatically update the Level Palette until the pane gets focus with a mouse over.

**Comment by jeremybullock** [comment]
Do we want to move this or remove this?

**Comment by onigiri1** [comment]
Other than level palette, 

The palette freeze button is useful if you want multiple palette panels with different **palette pages**

By default, tahoma will _always_ automatically update the Palette panel into selected color chip, and it's inconvinient if you want multiple palette pages to keep but the palette panel kept updating when you selected a chip from other pages (or levels)

**Comment by artisteacher** [comment]
If you keep it, I'd put it in the options menu so that it is out of the way. Or add a status bar message explaining the purpose.

**Comment by onigiri1** [comment]
> If you keep it, I'd put it in the options menu so that it is out of the way. Or add a status bar message explaining the purpose.

I'm afraid that moving it into options menu will make it inconvinient to be toggled

For suggestion, I'd say to move it to bottom along with other icons and add UI Toggle option to be hidden/shown
_Additional comment_ for it's icon, It could've been self-explanatory if the icon is a 📌 (pin) symbol

![tahoma freeze button](https://user-images.githubusercontent.com/46865843/96544140-28169c00-12d0-11eb-968f-33940ae5461b.png)
