### ISSUE TITLE
User-defined default Join setting (PLEASE!....)

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#353]
Hello...  Very often, I am building a shape, and notice ugly pointy edges extending out from my corners... only to realize that it is because the default Join setting of new shapes is pointed (Miter), when very often, I would prefer rounded.

Being able to set a preferred default would eliminate the need to change that setting for every new shape I create.

(In general, I would really like to see as many user-defined defaults available, to reduce/eliminate constantly having to tweek tool/item parameters before using them... or tweeking shapes after creating them.  Even if it is through manually editing a config file, if putting it in the Settings window is not ideal, it would be great...)

**Comment by jeremybullock** [comment]
It already remembers the last corner you selected.  Does that not work?

**Comment by ladlon** [comment]
It seems like I have to reset it often.  I'll have to verify it today.

Does it reset to a default (Miter) on every reload/relaunch?

**Comment by jeremybullock** [comment]
Just checked and it does remember the last used setting.
