### ISSUE TITLE
Optional node inputs shift when connecting [Already exists with CTRL]

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#354]
A helpful feature might be for when you insert a node output cable into an already occupied node input... where, rather than it disconnecting the pre-existing connection to allow the new connection to use that input, it instead (if, say, a modifier keyboard key is held) shifts all other connections 'below' that connection, down (including the one you are taking the input from), so that you not only don't lose the connection of the one cable, but you also don't lose the order of all the inputs.

Otherwise, unless there's some existing feature I'm not aware of, you would have to take every cable, starting from the lowest (vertically), and move it to the next input down, one by one, in order to move the target pre-existing connection down, opening up the intended input for the new connection.  Often, the stack order of the connections are important, so the ability to insert a connection 'between' two occupied connections would be very helpful.

For example: You have a node that has 3 inputs currently occupied.  You want to connect a new input so that it is after the first connection, but before the other two.  Currently, it would seem you'd have to move Cable 3 from input 3 to input 4, then Cable 2 from 2 to 3, and put the new cable/connection into 2.  For nodes that have many inputs (or if you have to keep adding new connections 'in between' the prexisting connections frequently), this could be a lot of busy work.

So, I'd think keep the current system as is by default (connecting to a occupied input disconnects the current cable, and puts the new one in its place)... but by holding down a modifier (CTRL?), it will instead move all cables (including the one you are about to use the input of) down one input, and place the new cable into the target input.

While were here, it would also probably be useful if you could select inputs and press keys to shift them down, opening up multiple inputs 'above' them.

It seems you can currently swap inputs... although it seems a bit odd, with the current system... It could use a bit more visual feedback as to what you are about to do.  I'm never quite clear on the current system... Is it RIGHT clicking and dragging?  Does that move the cable, or the cable AND the input?  A bit more clarity on the node wiring system might be good.

BTW, if a feature addressing any of thise already exists... then my apologies (...and could you point out how it would be done, then?)

**Comment by WolfInABowl** [comment]
Is this the sort of behavior you are referring to?
![Node Connection Insert](https://user-images.githubusercontent.com/42905003/95924639-de015800-0daf-11eb-8092-d81329a3825a.gif)

This is a behavior introduced in Toonz Harlequin 7 and can be activated via the CTRL modifier key.
https://youtu.be/M7ckY4ZyH-g?t=323
This is supported by any of the nodes that add additional inputs when a new connection is made, such as those in the `Layer_Blending` category.

**Comment by ladlon** [comment]
A bit hard to tell in the GIF, but ya, I think that's exactly it.

I'll have to try that out and see for myself.  Weird, I thought I tried modifiers already.  Are you just left dragging it, or right dragging it?  I was previously under the impression you are supposed to right drag the red arrow to swap the current cable with the destination (that you drag to).... but it always seemed a bit wonky.  That looks so much better, and has nice immediate feedback, it seems.

(Moments later...)  Okay, I tried it, but oddly enough, when I do it (with our without CTRL), it seems to temporarily erase all the cables below the initial target one when I drag it down.  I even sometimes get a vertical white line forming down to the left of the red triangles, as if it were connecting all the incoming cables together just before the inputs.

So, that probably explains why I didn't seem to notice this existing feature before... but I'm very curious now why it seems to be behaving differently than the example you are showing.  Yours looks great!

**Comment by ladlon** [comment]
(Mega-Face Palm)

Sorry, I'm an idiot...  I was using ALT, not CTRL.

Ya, that seems much better!

Cool.  That addresses some, if not all of my concerns with that.  I'll have to play around, and see if it's lacking anything I'd still like to see in it.

Thanks for pointing that out, and putting me back on the path, WolfInABowl.  Much appreciated!
