### ISSUE TITLE
Option for regular render without manditory save?

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#359]
Sometimes I want to try a drastic change in the scene and render it out, just to experiement with something... but I don't want to save the file (and lose the original).

Aside from saving a temp/test copy before rendering... or using the existing Quick Render feature... it would be great if we could just render without a save.

I get that the forced save is probably a safety feature, in case the render crashes... but the option to not save would also be helpful.

The Quick Render is great, but it only allows MP4, and sometimes you may want another format, even just for a temp test.

Just something I wouldn't mind having added...

**Comment by jeremybullock** [comment]
That will be in the next version.

**Comment by ladlon** [comment]
Awesome.
