### ISSUE TITLE
What does the 'half filled diamond' keyframe icon mean?

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#364]
The manual uses the older 'literal key' icon in its description of keys (in things like the settings window of an effects node), so I'm not clear on what the keyframe icon with only one half 'filled' means.

I think I've also had keyframe buttons (beside each of the various parameters of an effects node in its settings window) be a diamond with a dot in the middle, and then go to a 'solid' diamond if clicked again... and I wasn't sure what that meant either.  Was the first a 'there was no keyframe here before' keyframe, and the second was a 'there was previously a keyframe here' keyframe?

**Comment by manongjohn** [comment]
If it is solid, then all channels on the keyframe are set.  A half-keyframe means not all channels are set on the keyframe.  You would need to go to the Function Editor to see which channels are set.

**Comment by ladlon** [comment]
That makes sense.  Okay thanks.
