### ISSUE TITLE
Backlight node doesn't seem to work properly

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#366]
When I try and use the Backlight node, the 'light' effect not only appears in the expected 'rimlight' area (edges of item/shape), but also fills the entire background (alpha area).. which I assume it's not supposed to be doing.

I've tried multiple combos and sources, but I get the same effect.

It's hard to tell from the sample image in the manual if the effect covers the background, as both the rimlight and the sample's background are white... and I'm not sure if that white background is part of the effect, or just the neutral background display.

Meanwhile, the Body Highlight effect works just fine, not filling the background.  In the manual, the sample image for that also shows a white effect and a white background, ... but I know in THAT case, the background is not affected, so the white background in the sample is just a coincidentally similar coloured background to the effect colour... so, I'm assuming the Backlight one is the same.

But, I can't seem to get it to just rimlight the 'character' and not affect the background, too.  I think I even tried matting it using the 'character' as well.

Not sure if I'm doing something wrong, or if there's something bugged.  Seems I'm connecting things correct (based on the manual).

**Comment by jeremybullock** [comment]
This question would be better to be asked on the new Google group or in the Tahoma2D discord.
https://groups.google.com/g/tahoma2d
https://discord.gg/4HUXF6F

In the interest of clearing up the issue list here on GitHub, I'll be recommending this on a number of questions in the issues.
