### ISSUE TITLE
Windows packaging

### ISSUE THREAD

**Issue by manongjohn** [turtletooth/tahoma2d#369]
Few suggestions regarding Windows packaging since we don't currently package as an installer:

1. The Windows .zip files have everything at the root of the file so when extracting Tahoma2d, if you `Extract Here`, it will dump everything in the current directory, mixing with whatever files you might already have.

Suggestion: put everything in a `Tahoma2D` folder and then zip up the folder so regardless if a user extracts Here or into a different folder, everything will always be encapsulated in a Tahoma2D folder.

2. Name the zip file Tahoma2D-win.zip, at least in Github release page.

**Comment by jeremybullock** [comment]
I did this idea.  I'll do this for the next beta.
