### ISSUE TITLE
issue with next frame shortcut key

### ISSUE THREAD

**Issue by ratwhiskers** [turtletooth/tahoma2d#372]
**Describe the bug**
keyboard shortcut of next frame not working, it does not move to the next frame and if a frame other than the first one is selected it will jump to the first one

**To Reproduce**
List steps to reproduce the behavior.
1. set shortcut of 'next frame' to right arrow key
2. it does not work after restarting program n such, though the previous frame shortcut does
3. :( 

**Expected behavior**
timeline to move to the next frame upon pressing right arrow key
**Screenshots**

![image one](https://user-images.githubusercontent.com/73048411/96358234-c4b32100-10b9-11eb-860e-501e642b4b33.jpg)

**Device Information:**
 - OS: windows
 - Tahoma2D Version: tahoma 1.0.1
 - GPU: unknonw
 - GPU Driver Version: unknown

**Comment by artisteacher** [comment]
I can't use any of the arrow keys for shortcuts on macOS.

**Comment by jeremybullock** [comment]
The arrow keys or space shouldn't be used as keyboard shortcuts.  The arrow keys are already configured to navigate through frames.

**Comment by jeremybullock** [comment]
#373 Should take care of this.
