### ISSUE TITLE
Add Recent Project list in Switch Project dialogue box

### ISSUE THREAD

**Issue by onigiri1** [turtletooth/tahoma2d#380]
**Is your feature request related to a problem? Please describe**
Everytime when you want to switch to previous project, you have to repeat the process of navigating into your project folder in File Browser

**Describe the solution you'd like**
Add Recent Project list in `Switch Project` dialogue box

![Recents Project list tahoma](https://user-images.githubusercontent.com/46865843/96405324-30ef6b00-1207-11eb-83de-3a9a097ee77d.png)

**Comment by artisteacher** [comment]
That would be helpful! 

On a related note, I'd love to be able to set a specific directory as a parent/root directory for projects. Ie. If I set the parent to Documents/Animations, whenever I make a new project, it would automatically save in Documents/Animations, unless I choose to set a different location. That could also make navigating to different projects easier in the browser.

**Comment by DarrenTAnims** [comment]
Thanks @artisteacher. I couldn't agree more. Setting the default project folder or having them as a recent list would be so helpful. I create all of my projects in Documents/Tahoma, but I have to add or browse down to the Tahoma folder every time.
