### ISSUE TITLE
Changes to Sound for Windows for 1.2

### ISSUE THREAD

**Issue by jeremybullock** [turtletooth/tahoma2d#382]
Hey anyone who reads this!

I am looking at removing the windows specific sound code that we currently use and having all sound playback handled by qt (tsound_qt.cpp).  The code in tsound_nt seems like overkill when the qt solution works fine.  If Tahoma2D were a full fledged compositor, having platform specific audio code would probably be necessary, but I don't think we need it.

@manongjohn Do you have any thoughts on this?

**Comment by DarrenTAnims** [comment]
It makes sense to re-use the library that we've already got installed, if it's not a huge re-write. Will using QT offer any new features or will it just be "cosmetic" tidying up?

**Comment by beeheemooth** [comment]
How does it sound in human language? We will not be able to use sound, or record it, or something else?

**Comment by jeremybullock** [comment]
@beeheemooth This is just an under the hood change.  It won't change the abilities of the program.  I've already implemented the change in a pending pr.  I think it made scrubbing more responsive and I took care of a memory leak in the process.
