### ISSUE TITLE
Fill when I draw or erase(vector layer)

### ISSUE THREAD

**Issue by NothingAnimated** [turtletooth/tahoma2d#388]
**Describe the bug**
When ever I draw or erase in certain places on the stick figure, it fills the arm with gree

**To Reproduce**
I don't really know

**Expected behavior**
To just be able to draw/erase

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/69369888/96618651-35815580-12d3-11eb-8a6e-be0ade4fa84c.gif)

**Comment by artisteacher** [comment]
There are known issues with vector fills behaving strangely in some cases:
https://github.com/opentoonz/opentoonz/issues/2302
https://github.com/opentoonz/opentoonz/issues/2321
https://github.com/opentoonz/opentoonz/issues/2741

**Comment by NothingAnimated** [comment]
Is there a fix?

**Comment by jeremybullock** [comment]
It is often best to fill your work after you are done drawing.  Tahoma calculates the regions for filling as things are drawn.  Sometimes the detected region changes as you draw.

**Comment by jeremybullock** [comment]
Another option is to use grouping to keep fills tied to a particular stroke/strokes.
There is an autofill and autogroup feature in the 1.1 beta.

**Comment by NothingAnimated** [comment]
I also tried to erase something and it filled the entire face, I wanted to erase part of the hair and it filled in the entire face

**Comment by manongjohn** [comment]
Keep in mind that in Vector levels, fills are dynamic. If you move a line, the fill adjusts itself to meet the lines. The fill is not a static object. Adjusting endpoints, adding or erasing lines or parts of line will similarly impact how things fill.

Having said that, vector filling is known to be a bit tempermental/buggy due to issues with how the application handles line intersection and fillable region calculations. Some tricks like grouping can help.

**Comment by NothingAnimated** [comment]
What is grouping (I am a newer tahoma user.

**Comment by artisteacher** [comment]
A stroke (or strokes) in a group will ignore strokes outside of the group. So anything outside the group will not have an impact on the fillable region. The entire group can be selected and moved/adjusted as one. 

CMD+G or CTRL+G makes a group of the selected stroke(s). There are also group options in the Edit menu. If you turn on auto-fill in the 1.1 beta, closed shapes will automatically be in their own group.

**Comment by NothingAnimated** [comment]
is this a bug, or just how vectors work?

**Comment by jeremybullock** [comment]
Right now, it's just how vectors work.  Using grouping is a great way to work around it or you can do your filling after you have your line work finished.
