### ISSUE TITLE
Crash on Mac when selecting raster brush

### ISSUE THREAD

**Issue by phillvancejr** [turtletooth/tahoma2d#399]
**Describe the bug**
Tahoma immediately crashes when trying to select a raster brush

**To Reproduce**
List steps to reproduce the behavior.
1. select a raster brush

**Expected behavior**
no crash

**Screenshots**

**Device Information:**
 - OS: Mac Mojave
 - Tahoma2D Version: 1.0.1
 - GPU: AMD FirePro D300

**Comment by manongjohn** [comment]
This is likely the same as #339

**Comment by jeremybullock** [comment]
@manongjohn Does your build have the same issue, or would it be worth trying that one out.

**Comment by manongjohn** [comment]
@phillvancejr  The beta build that is out now (https://github.com/turtletooth/tahoma2d/releases/tag/v1.1-beta.1) was built on 10.13, so it should be fine for 10.14.  Please try using that and see if you are still having problems with the Raster tab.

**Comment by phillvancejr** [comment]
@manongjohn The linked beta build works without crashing. I think this can be closed now
