### ISSUE TITLE
Changed project doesn't always show as active from startup popup

### ISSUE THREAD

**Issue by artisteacher** [turtletooth/tahoma2d#403]
**Describe the bug**
Opening another scene after changing the project from the startup popup, still shows the old project.

**To Reproduce**
List steps to reproduce the behavior.
1. Open Tahoma
2. Change the project to a different, existing project
3. Click on "Open Another Scene"

**Expected behavior**
For the newly selected project to be active in the browser - it's not, the old project displays as active.

**Screenshots**
<img width="500" alt="Screen Shot 2020-10-21 at 9 18 24 PM" src="https://user-images.githubusercontent.com/21159116/96806871-2f7a9a00-13e3-11eb-94ac-20c6fb46b51e.png">

**Device Information:**
 - OS: macOS
 - Tahoma2D Version: master 10/21.20

**Comment by jeremybullock** [comment]
What project does the "Open Another Scene" scene belong to?

**Comment by manongjohn** [comment]
When you "Open Another Scene", if it isn't in the current project, normally you have the option to import it into the current one, or switch to that project.

**Comment by artisteacher** [comment]
Sometimes I want to open a scene from an inactive project that hasn’t been used recently. If I change the project first & then choose “open another scene”, I want to choose a scene from the newly active project. However the old project displays as active & I have to navigate more than necessary to find the project & scene I wanted. 

I know you can skip changing the project first, use “open another scene” and just find the correct scene. The project will automatically change. But if I do change to the correct project first, it should show as the active project in the “open another scene” browser.

**Comment by jeremybullock** [comment]
I see what you are saying.  Right now, when you "change the project" from the startup window, it doesn't actually change the project until you create the scene.  I'll see if I can change that to update right away.
