### ISSUE TITLE
Create Blank Drawing command does not use default palette.

### ISSUE THREAD

**Issue by melieconiek** [turtletooth/tahoma2d#404]
**Describe the bug**
After triggering `Create Blank Drawing` in an empty column the resulting new level is not assigned the default palette.

**To Reproduce**
1. Select an empty column.
2. Trigger `Create Blank Drawing`

**Expected behavior**
The new level should use the default palette.

**Screenshots**
![_demo](https://user-images.githubusercontent.com/42298081/96927611-4e316d00-1485-11eb-983b-eef7ed09acb9.gif)

**Device Information:**
 - OS: Windows 10
 - Tahoma2D Version: Latest Commit (10-21)

**Comment by jeremybullock** [comment]
Sorry.  This is my doing.  I merged a PR from OT that did this.  @manongjohn unless you already have a fix underway, I can take this.

**Comment by manongjohn** [comment]
This was a result from PR #391 which incorporated the "Fix Crash When Drawing on Absent Level # 3541" from OpenToonz.

The initialization of a new frame on a newly created level is forcing a non-user defined default palette to be assigned to the level, replacing the default one that was assigned.

I will submit a fix as soon as I can after I review the potential impact of this change in other places that might not be obvious.
