### ISSUE TITLE
Tahoma Brush resize shortcut using Shift and Cmd + Shift with dragging

### ISSUE THREAD

**Issue by phillvancejr** [turtletooth/tahoma2d#408]
**Is your feature request related to a problem? Please describe**
In Opentoonz we can resize the brush by dragging while holding cmd + alt, but this has been replaced in Tahoma2D with the vanishing point tool which is fine because the Opentoonz method does not feel intuitive at all and is too sensitive and difficult to control for me.  Krita uses the shift key while clicking and dragging horizontally to control brush size and it feels very intuitive. It would be nice to have this feature in Tahoma instead of having to use the U,H,I and J keys.

**Describe the solution you'd like**
In Tahoma i would like to see the Shift key with horizontal dragging used for brush size as follows:

raster brushes - Shift + horizontal drag (left negative, right positive)
vector brush max - Shift + horizontal drag (left negative, right positive)
vector brush min - Shift + CMD/CTRL +  horizontal drag (left negative, right positive)

This does bring one conflict, which is that currently shift is used for straight lines with the brush tools. With vector brushes Shift allows drawing straight lines with arbitrary values and CMD/CTRL allows for straight lines that snap to angles, however with raster brushes if you start drawing with CMD/CTRL then release CMD while still moving the mouse, it functions the same as the Shift version, meaning that with raster brushes the shift shortcut is unnecessary. To fix this conflict, make straight lines with vector brushes work the same way that raster brushes work, i.e.:

straight line snapped to angle - (hold) CMD/CTRL + drag, move to desired angle (while holding CMD/CTRL), release mouse button/lift pen to draw line
straight line with arbitrary angle - (press)CMD/CTRL + click, release CMD/CTRL, move to desired angle, release mouse button/lift pen to draw line

**Comment by jeremybullock** [comment]
I like the idea of quickly being able to change the brush size, but I think losing shift as a straight line with the workaround you mentioned above isn't as user friendly.  I am open to other suggestions.
