### ISSUE TITLE
Plastic Tool no longer animating

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#418]
Previously did work (animated fine).

Currently, the mesh/bones work correctly, live... but when keyed, no animation occurs, as if no keys were set.

I tried deleting the mesh, and rebuilding it, but the same issue occurs.

I tried creating a new column, and creating a mesh for it, but still the same issue.

I tried with Global Keys checkbox on/off.

Timeline/Spreadsheet shows keys and values within/between them.  Everything fine except that keys do not hold their values, but instead the bones/mesh simply stay at whatever the last position/distortion was set.

My guess would be some sort of 'residue' values/flag interfering, although I even manually deleted the mesh file in the Drawings folder.

Nothing seems to fix it now.

What may have somehow triggered it is:

I had a working column/drawing and matching Plastic Tool mesh for it.  Distorted properly, and animated fine.
I later added a second drawing (slight modification of the previous), changed the column to use that second drawing instead of the first (initially keeping the first drawing as a backup).
I eventually deleted the mesh column, and rebuilt one for the same (drawing) column.
Again, everything worked fine, but now it wouldn't animated.  Live manipulation worked fine (distorted drawing), keys could be set (and everything looked fine in the editors), but no animation would occur (acting as if no keys were set, and whatever bone manipulation I did would simply stay throughout the entire timeline range, despite actual keys being present).
So, all I can think of is there's some 'residue' element in this scene that refuses to unhook from the previous mesh or drawing(?)

As best as my understanding goes, I deleted all relevant/old files that might be causing the problem (in the Drawings folder), and did a full save (hoping that might refresh/reset the hooks), but again, nothing seems to fix it.  I can't seem to even successfully create an animatable mesh with a new column and new mesh.

Previous mesh/drawing (in the same project file) worked fine.  All seemed to start when I added a second drawing to the 'drawing' column (of which the mesh was associated with).  Figured that MIGHT cause issues, but also figured that completely redoing it (new column, newly made mesh for it) would avoid any residue/association with the broken mesh system).

Tahoma 1.0.1
Win7Pro

**Comment by artisteacher** [comment]
I think I've run into this two, though I'm not sure what triggered it.

**Comment by ladlon** [comment]
Hi, artisteacher.  I did some more tinkering... like seeing if I could animate it by adding keys from within the graph editor and spreadsheet.  Some more weirdness there, too.  I was able to make an initial keyframe in the graph edtor... but then when I wanted to make another key further down the 'timeline', I noticed that the key button and frame field had vanished (and it was just the value field at the top of the graph editor.  The spreadsheet also had random weirdness.

I tried a whole bunch of random things in the graph editor and spreadsheet, and at one point made some 'progress'... in that I managed to get a second key in there... but it seemed initially like there was no line/curve between it.

Looking into it further, I think what was happening was that it was set to Constant interpolation (despite my default being set to Speed)... and so the line was effectively 'invisible' (...which is pretty easy, since the lines are pretty hard to see as it is).

After a while, I was able to have two keys (in the graph editor) with a Speed interpolation, AND (finally) it appeared they were causing animation.

I thought then maybe my original (failed) attempts were mysteriously set to constant interpolation... but that still would result in the mesh at least snapping to the new position when the time marker was at/past the second key... which it didn't do.

I'll tinker some more, but this is very frustrating.... (and, unfortunately, I'm in the middle of a big project).

I'll post here if I spot anything further, but I was just hoping for some theories, or things I could try (ex. Delete this file, run this command on these keys, etc).

**Comment by artisteacher** [comment]
You might want to double-check the schematic view - make sure the mesh is still the parent of the column.

**Comment by ladlon** [comment]
I've now managed to kick it somehow so that it is allowing animating keyframes... although it doesn't appear to be honouring the default setting I made of new keys getting Speed in/out interpolation (...putting them to Linear instead... and having some weirdness with the handles when I DO set them to Speed).

Ya, I checked the schematic long before, and even reversed the parenting order (since I wasn't fully sure it the drawing should be parented to the mesh, or vice versa... and figured maybe that was the issue).

I think it was some weird hangup involving the interpolation, and the overall weirdness I have been finding with the sort of 'contextual' nature of a lot of Tahoma's functions (...for lack of better description of the quirkiness I'm experiencing).

I'm currently able to animate that mesh... although it's doing weird things... like I keyframe at 0 and 20, and then set a key at 10, and do a change on 10 (distort the mesh by moving a bone), sometimes it seems that frame 20 (which should be the same as 0) has somehow changed.  I can't narrow it down to anything specific, as it's been kind of random.

At least I'm (so far) able to animate that mesh.  I 'kicked' something that seems to have now allowed me to proceed... sort of.

**Comment by artisteacher** [comment]
How are you adding the initial keyframes?

**Comment by ladlon** [comment]
Usual ways... selecting the mesh column, selecting the Plastic tool, hitting the keyframe button at the bottom of the viewer... or using the Set Key hotkey... or even giving one of the bone nodes a nudge.

Just a lot of random weirdness... like SOME of the curves ending up linear... and sometimes (after switching a curve to Speed), it makes the outgoing interpolation 'linear' (0 speed, no handles)... and many attempts to set a value which would result in a curved slope and handle appearing just get zeroed when I hit Apply.

I wish I could give you a more focused 'cause and affect', but it's just so random right now.

**Comment by artisteacher** [comment]
So the keyframe button in the bottom of the viewer doesn't seem to actually set keyframes for the vertices when the plastic tool is in animating mode. I wish it did...I think that's the expected behavior.

Instead, set the outermost keyframes through the viewer context menu - I recommend choosing "Set Global Key".  Then adjust the vertices on frame 10 or etc.

**Comment by ladlon** [comment]
I just checked it over here...  It seems to set a key, but it doesn't animate!

I'm avoiding the global key thing, as I'm already having severe trouble dealing with digging through the existing (animated) keys, so I'm avoiding anything that creates more (unnecessary) animated channels to take up space and visually distract.

**Comment by ladlon** [comment]
Oh, you mean do a Global key for the initial one?  Ya, I've done that sometimes.

**Comment by ladlon** [comment]
Yup, understood...  I normally do that.  It's just (partially) due to Tahoma2D's tendency to display every channel (unless you manually deselect them every time you open the editor) that motivate me to not just do global keys on everything.

I'm really hoping that someday a way to just have the editors show only the relevant channels is added (ex. what you have selected in the timeline before launching an editor... or having the editor show only the item you click on in the channel list, etc).  The randomly cluttered editors, and the tedious way you seemingly have to deslect all the (seemingly) randomly selected/hilighted  channels each time the editor is opened is a serious pain.  Finding and managing to select curves in the clutter of multiple channels is a serious burden to workflow for me.  I wish I could just click on an item in the channel list, and the curve appears (solo'd) in the display (...with the ability to Shift/CTRL-click other channels to add to the display as needed).

**Comment by artisteacher** [comment]
> I'm really hoping that someday a way to just have the editors show only the relevant channels is added 

I really hope so too!

**Comment by ladlon** [comment]
Okay, well I guess no one else is likely to chime in on this, and I (at least currently) got it allowing me to animate the mesh, so I'll close this, so it doesn't end up as a long thread.  Cheers...
