### ISSUE TITLE
Customizable UI/Curve colours

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#423]
RGB sliders to customize curves and even UI elements.

(I know that you can modify UI elements via the config file, but it's pretty hard to find/destinguish what code areas are specifically the ones you are after)... plus it would be ideal to be able to make those modifications in-app.

I'd also love to see a separarate RBG slider for the viewer background specifically... as sometimes your animation content is hard to see against even the available Themes (plus sometimes you want to keep the UI as is, EXCEPT for the viewer bg.

I generally prefer the darker themes, but when editing drawings that are dark (such as lines/non-filled outlines), it's difficult to see them against the viewer background.

Being able to customize the colours individual Graph Editor curves would GREATLY help in being able to quickly spot them, since currently many curves share the same colour.

**Comment by artisteacher** [comment]
You can already customize the viewer bg color in Preferences -> Color

**Comment by ladlon** [comment]
You are absolutely right.  I totally missed that.

Sorry about that, and thanks for pointing that out!
