### ISSUE TITLE
Ability to render 'viewer' version of aniamtion

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#424]
For quick motion tests (and overall quicker WIP renders), it would be great to be able to render FX-free (non-Preview mode) versions of the animation (as seen in the viewer)... without having to manually rig up a secondary output in the Schematic.

Either a viewport version, or ideally a 'schematic' version, but with all (processing type) nodes deactivated... or at least the ones that typically slow down renders.

**Comment by artisteacher** [comment]
Try using the export panel.

**Comment by ladlon** [comment]
Hi.  I see it, but I'm not clear on how to 'drag a scene' to it.

I couldn't find anything on it in the current manual.

**Comment by artisteacher** [comment]
Use the browser room - you can drag a scene from there.

**Comment by ladlon** [comment]
Ah!  Okay, ya, that works.

Although, interestingly, it says it can't export anything that uses a Plastic Tool mesh... Weird, as the viewer is capable of processing it without needing 'Preview' mode.

What exactly does the Export feature (from the Export panel, not the File pulldown menu) do exactly?  Is there mention of it in the current manual?  The search doesn't bring up anything of the Panel version, and I couldn't find anything in the render sections or the interface sections.  Is there reference elsewhere?

**Comment by artisteacher** [comment]
I think there was crash when exporting plastic mesh modified levels, so it's been disabled for now. It renders without applying FX.

It had been removed from OT early on & was brought back in Tahoma. Toonz manuals might have documentation.

**Comment by ladlon** [comment]
Okay, I'll look further into that.  Thanks again, artisteacher.
