### ISSUE TITLE
Ability to set keyboard shortcut for Set Marker In/Out points

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#435]
Not sure why it isn't available in the Shortcut Editor window... but it would be nice to be able to set a keyboard shortcut to set the in/out markers.

(Granted, you can use the RMB menu... but keyboard shortcuts can be much faster and/or easier)

**Comment by artisteacher** [comment]
#324 - coming in 1.2

**Comment by ladlon** [comment]
Looks like 1.2 is shaping up to be a really great update!

Any ballpark on when it might be arriving?  (Or how far along it is?)

**Comment by jeremybullock** [comment]
This has been implemented.
