### ISSUE TITLE
A sort of 'Erase the drawing keys in the selected frames' feature

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#441]
If I have a column with a number of (drawing) keys on it, and I want to 'erase' the keys in a certain section... one way to do it is simply select that area, delete the occupied cells (leaving the gap), select that area again, and then use the Fill Empty Cells feature to fill it with the drawing occupying the keyframe before the gap.

All well and fine...

But, I'm thinking it would be great (to save several steps) to be able to do the same thing by simply selecting the section, and then triggering a feature that fills that range with non-keyed copies of the drawing previous to the edit area...  effectively erasing the (drawing) keys, and having the drawing (of the key before the selection) continue through the whole selection area.

A fast and easy way to just clear areas in one click.

**Comment by artisteacher** [comment]
We can already do this a little faster then how you describe:
- Select the cells to remove & delete
- With the same selection still active, press Q to fill with the previous drawing (or W to fill with the next drawing)

**Comment by ladlon** [comment]
Hi.  I've changed many of the keyboard shortcuts, so I'm not sure which command you are referring to.

Is it the Substitute Drawing Up/Down one?

If so, that doesn't seem to work (in the way you describe)

**Comment by artisteacher** [comment]
Drawing substitution backward

**Comment by ladlon** [comment]
Sorry, that's the one I meant.

Ya, I remapped that (up/down arrows)... and that works to cycle through the drawings... but if I do a multi-cell selection (that contains a few drawing keys) and use the Substitute Drawing Backward/Forward, it doesn't replace all the different (keyed) drawings with a single drawing.  It just changes one of the keys/drawings, but leaves all the other cells in the selection unaffected.

**Comment by manongjohn** [comment]
Another way to do this is to select the cells, delete them, then right click the last empty cell and use `Fill In Empty Cells`.  Likely a better choice if the previous drawing isn't close to the drawing you are on.

**Comment by ladlon** [comment]
When I originally tried it (long before) I was kind of hoping/expecting it to do that... change ALL the selected cells, as it cycles through the drawings... like how it does with a single cell, but changing ALL the selected cells (having them have all the same (current) drawing in the cycle).  I was really disappointed when that didn't seem to be the case.

**Comment by ladlon** [comment]
Re: Fill Empty Cells method...   Ya, that's sometimes how I do it... but, my point is, that's a muti-step system, and I'm suggesting a simply 'Select cells, and use 'Erase drawing keys' kind of thing, where it simply fills the area with the drawing of the nearest key above/left of the selection area.  Single 'click' system.

One of my peeves of Tahoma2D, is that it seems to sometimes require some unnecessary cleanup/busywork...   Move something, but then have to compensate for the shift by adding something on the other side... That kind of thing...  Or things being a multi-step process, when the command itself should do the 'cleanup'.

**Comment by ladlon** [comment]
I'd be really curious to hear how you are getting the Substitute Drawing Forward/Backward thing to work with a selection of keyed cells.  That would be awesome if it worked like you describe.

**Comment by artisteacher** [comment]
![demo](https://user-images.githubusercontent.com/21159116/97629747-e939c200-1a04-11eb-9e06-83f9879cbab2.gif)

**Comment by ladlon** [comment]
Oh, okay, you are deleting them!  Your description made it seem like you just select them and hit Q.

Ya, okay, sure that works, but that just illustrates my point... multi-step process.  Whereas I'd love to see a simple 'Select and 'erase keys' functionality.

Werid thing is, even when I try your method, it still doesn't work as it does in your vid.  After I delete the cells, pressing the Drawing Substitution Backward key does not fill in the gap.  At best, one cell gets filled... but usually nothing gets filled.

**Comment by manongjohn** [comment]
> One of my peeves of Tahoma2D, is that it seems to sometimes require some unnecessary cleanup/busywork.

Yes, there are tons of inefficiencies in the software...every software has that and every user has their opinion on how something should work or would like it to work.  This software was built from OpenToonz which was built for and used by animation studios. and for whatever reasons they have, they kept it that way, inefficiencies and all.

I'm not disagreeing about the feature request and I understand where you are coming from, but we are just pointing out possible ways to do it until someone comes along and improves things per your request.  So please take our suggestions as a workaround in case you are doing things the long way and don't know a better method yet.  We can't always tell what you've tried or how you are using the software.

**Comment by ladlon** [comment]
Yep, understood.  I'm all for workarounds... but I can't seem to get it to function as it is in the sample video.  I wish I COULD!

I keep trying it over here, and I get as far as the deletion... but when I then try and fill the gap using the drawing substitution command, it does either nothing, or just fills one cell.  I'm trying to figure out what the difference is between our two scenarios.

I'm using 1.0.1...  Is this some beta addition?  What could possibly be the difference in our two scenarios?

**Comment by ladlon** [comment]
![NoFillingWithDrawingSubst](https://user-images.githubusercontent.com/71803483/97632402-d32e0080-1a08-11eb-888a-070bb1c47255.gif)

Here's me trying... although the vid doesn't really help here, as you can't see me hitting the Substitute Drawing Foward/Backward keys after the delete.

**Comment by artisteacher** [comment]
I'm using a MacBook Pro. The delete key we have is equivalent to backspace on non-apple keyboards. So to get the pc equivalent of delete, I have to use Fn-delete. I think that should be the same thing as delete on non-apple keyboards.

This method always works for me, unless I'm deleting a keyframe at the same time. For some reason selecting and deleting the frames & keyframes together, prevents the drawing substitution command to work with the active selection.

**Comment by manongjohn** [comment]
Here is my example:

1. Select a range 
2. Use Drawing Substitution Backwards shortcut (Q)

![replace-range](https://user-images.githubusercontent.com/19245851/97632303-b4c80500-1a08-11eb-88a8-a84f23fd2618.gif)

Keep in mind Drawing Substitution Backwards/Forwards may require you to hit that shortcut a few times to get to the desired image, if the images are not next to each other.

**Comment by ladlon** [comment]
@artisteacher: Weird... Ya, I can match your process up to after the delete.  Then, it seems the substitute drawing feature works differently between mine and yours.  I WISH I could get it to work like what you are doing.

@manongjohn: Ya,I can do that... That's not what I'm after.  You are just changing a single cell.  I do that constantly, and it works great.  I'm talking about if you have a bunch of (drawing) keys, and you effectively want to 'erase' them, so that the drawing previous to them keeps going through that edit/selection range.  What artisteacher's vid shows it what I'm trying to do.  But, in my case, after deleting, the (Q) function does nothing (or just changes ONE cell... leaving the gap (from the delete) there.  I really wonder what is different between artisteacher's scenario vs mine.  Seems we are doing the same thing, but getting very different results with the Q key.

**Comment by artisteacher** [comment]
Are you still using the arrow keys for the drawing substitution commands? Since they are hardcoded to navigate the Timeline/Xsheet, that could be interfering with the proper behavior for drawing substitution.

**Comment by ladlon** [comment]
Ya, I ran into that issue before... yet, now there seems to be no conflict.

I have left/right arrow to move up/down the timeline... and up/down to cycle through the drawings (so I can rapid-fire move and set keys for things like lipsync).  I have 'Fill Empty Cells' as the slash, which I can thumb-tap while keeping my right hand on the arrow keys.  Works great, and for me is very intuitive and natural.

I could try deactivating the custom keyboard shortcuts for the drawing subs as a test.  That would be interesting (although very disappointing) if the functionality were getting interfered with, due to the custom keyboard shortcuts.

**Comment by manongjohn** [comment]
As this conversation is going beyond the feature request and adds nothing for a developer who may want to work on this, I ask that you please continue this discussion on the forum or get on a discord and hash it out in more real time with other users.

**Comment by ladlon** [comment]
Agreed.  I'm on the Google page, too.  I do all my questions there.  It's just sometimes the Feature Requests and Bug Report posts get a discussion due to the need for explanation, etc.

Can I keep this 'open' (but not add to it), or will the developers still see the suggestion if it is 'closed'?

**Comment by manongjohn** [comment]
Please keep it open.  it is a feature request that has some value.  Just need to go back and hide Off Topic comments.

**Comment by ladlon** [comment]
Done.  Thanks.

**Comment by jeremybullock** [comment]
I'm not sure I see this as a request that meets a need common enough to warrant it's own command.
