### ISSUE TITLE
Ability to drag (translational) key on top of existing key

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#443]
Currently, if you move a translational (as opposed to 'drawing') keyframe over an existing translational key, it hops over it to the cell on the other side.

While I understand why you might want to prevent it going on top of the key, as a 'safety' measure, so the second key doesn't get replaced, it seems it might be smarter to simply allow it... as the user will surely see there's a key there anyway, and not drop the moved key on top of it (if they want to keep that second key).

There's many instances where you would actually WANT to replace that key with the (moved) key... and currently, the system simply won't let you do that, and you're forced to manually delete that key (remembering what frame it was on) and then grab and drag the (moved) key to that spot.... rather than just being able to drag the (moved) key and drop it on top.

Just seems like a safety measure that really isn't needed, and prevents you from doing a pretty common edit.

**Comment by artisteacher** [comment]
Or just cut the key you want to move and paste it on the existing key to replace it.

**Comment by ladlon** [comment]
Sure, but again, it's a multi-step process... rather than just a more natural single step 'drag on top'.

A lot of my suggestions aren't about 'you can't do this'... but more of 'this can be done with less steps or fuss'.

**Comment by artisteacher** [comment]
I don't disagree - just mentioning another way to get the same effect in the meantime.

**Comment by RattusaurusRex** [comment]
If you press Alt and then click on the key to move it, you can replace other keys.  Additionally, Shift will insert and Ctrl will copy.

**Comment by artisteacher** [comment]
Good to know, thanks!

**Comment by ladlon** [comment]
But my point is, the ALT seems redundant.  Why not just drag it (no modifier), and if you want to replace a key with the key you are dragging, just drop it on top (no modifier).  If you don't want to replace it, then you drop it elsewhere.  There's no other scenario if you drop it on top of an existing frame... it WILL replace it, always.  So, why the need for a modifier key?

Drag (unmodified) a key anwhere to relocate it.  If you drop on top of an existing key, it replaces it.  Holding down Shift or Ctrl will do their functions as they currently do.  Just lose the (redundant) need to hold down the ALT key.

**Comment by jeremybullock** [comment]
Using alt helps prevent accidental loss of a key.

**Comment by ladlon** [comment]
Sure, but is it that high of a risk?  The same risk could be said of any other procedure, too.  Seems like an unnecessary precautionary procedure.

**Comment by jeremybullock** [comment]
I think we are going to leave this one as is.
