### ISSUE TITLE
Can't export without it closing itself.

### ISSUE THREAD

**Issue by Holly1001** [turtletooth/tahoma2d#444]
**Describe the bug**
The bug is that when I try to fast export to MP4, it only gets partly there before closing itself.

**To Reproduce**
List steps to reproduce the behavior.
1.Open project
2. Click  'fast export to MP4'
3.

**Expected behavior**
It should export without closing itself.

**Screenshots**

**Device Information:**
 - OS: Windows
 - Tahoma2D Version: version 1.0.1
 - GPU: [e.g. NVIDIA RTX 2080]
 - GPU Driver Version: [e.g. 440.00]

**Comment by manongjohn** [comment]
Does it crash at the same point each time? Are you using vector levels and keeps dying on a particular frame?

Have you tried increasing `Preferences -> Import/Export -> FFmpeg timeout`?  Depending on how long your animation is or maybe even how complex is, the default 600 may not be enough.

**Comment by artisteacher** [comment]
Is there a crash log for Tahoma in the Event Viewer under Applications?

**Comment by jeremybullock** [comment]
Thank you for the bug report.  There are known issues and open bug reports regarding rendering, so I'm going to close this and keep the original rendering bug report open.
