### ISSUE TITLE
the layout of tools.

### ISSUE THREAD

**Issue by fatlemoncat** [turtletooth/tahoma2d#445]
when I opened the program, all the tool features and timeline was zoomed in and the canvas was small for some reason. When I
 tried fixing it the canvas size became normal but there were no tools, timeline or colour wheel. I can't seem to find the solution and I do not know if it is just a bug, or it is just my computer. I really appreciate if I can get this fix.

**Comment by manongjohn** [comment]
Can you provide screenshot? Is this on a display tablet or monitor?

My guess is the resolution scale of your monitor or tablet is set high. Putting it around 100-125% might help.

Not sure how you tried to fix it that would cause the other panels to disappear.

**Comment by DarrenTAnims** [comment]
It sounds like you dragged the viewer out of the docked view and its size just made it sit in front of your other tools. I'd suggest you reset your layout (from the Panels > Reset option) to get back to the default view.
