### ISSUE TITLE
You might want to change the Questions link on the official Tahoma2D webpage

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#455]
The Ask Questions link on the Tahoma2D website (Support section) still currently points to this GitHub forum.

Seeing as you don't want this forum flooded with noobie questions and other things you'd rather be asked on the new Google Group page, you might want to change the URL on that link... as it is currently the only 'support' link presented to anyone getting Tahoma2D from its official website.

Obviously, if you still want a specific type of question to be directed to the GitHub forum, a second, more specific link should be added.

**Comment by jeremybullock** [comment]
Done.  Thank you for the suggestion.
