### ISSUE TITLE
Ability to set more than one keyboard shortcut for a command

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#456]
Title pretty much sums it up.  I, for example, wouldn't mind having the Set Key button on a key on either side of the keyboard, so I can switch around my hand position, depending on what I am working on.

Granted, you can define two (or more) separate shortcut config files, but it would also be great to be able to have multiple key options wtihin the same 'session'.

**Comment by jeremybullock** [comment]
Unfortunately I think the request here is beyond the scope of what I have in mind for the program.  I'm sorry for not being able to implement this.
