### ISSUE TITLE
Ability to key multiple columns at once

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#457]
I was actually surprised you couldn't do a multiple selection and then key everything at once, rather than having to individually key each column one at a time.

**Comment by artisteacher** [comment]
While you can't add keyframes to multiple layers based on a selection, you can still make keyframes that impact all the layers if they are all in a sub-scene or if they are attached to a pegboard.
<img width="468" alt="Screen Shot 2020-11-04 at 9 59 00 PM" src="https://user-images.githubusercontent.com/21159116/98192498-21e80880-1ee9-11eb-89d1-79b4c280e527.png">
In the stage view of the Schematic panel, add a pegboard. Connect the layers you want to key together to the peg. Make sure the peg is selected in the animate tool & then make your keyframes.

**Comment by RodneyBaker** [comment]
We can key multiple columns at once... although it's a 'key everything' option.
The command is 'Insert Multiple Keys' and is available via Right Click menu when cursor is over the frame number.

![image](https://user-images.githubusercontent.com/2576432/98366313-619e1580-1ff9-11eb-9781-c1cf60abac7e.png)

This is the equivalent of a 'force keyframe' in some programs and basically locks down all transforms for that frame.

**Comment by ladlon** [comment]
Ya, what I am suggesting/requesting is the ability to select multiple items and then do specific keys (ex. positional)... for example, selecting mutliple items, moving them together, and having the autokey key all of them.

The multiple keys keys all channels, as you say... and the peg system works, but is only really good for specific groups you predetermine you want to move together, rather than the ability to select different arrangements of groups on the fly.

This is just an additional ability I'm suggesting, similar to what you'd find in other programs.

**Comment by jeremybullock** [comment]
Unfortunately I think the request here is beyond the scope of what I have in mind for the program.  I'm sorry for not being able to implement this.
