### ISSUE TITLE
Key Sets

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#458]
One feature from the 3D world I think would be a good addition to Tahoma2D is the concept of Key Sets.

Basically, you define a list of items, and when you press the Set Key button, it keys all of those at once.  In the case of Tahoma2D, you'd define a list of channels from various columns.

This is a really great way to quickly set multiple keys, which you know you'd be keying very often.  Kind of like a Global key, but with multiple items (columns), and not keying channels you don't want keyed (as Global keys often do).

**Comment by jeremybullock** [comment]
Unfortunately I think the request here is beyond the scope of what I have in mind for the program.  I'm sorry for not being able to implement this.
