### ISSUE TITLE
Touch Screen Support and GUI

### ISSUE THREAD

**Issue by DoodleScrib** [turtletooth/tahoma2d#461]
My idea was that there could be a mode or button that lets users of Cintques or Surface users change the way you can traverse the program, as well as allowing touch drawing, and multi touch gestures and such. I suggest this as I know that I draw more consistently with my fingers, and as such, I invested in a Surface tablet. I am learning to use my separate drawing tablet to be more consistent, as I mostly use the keyboard with the tablet (using it more as a laptop) but would love the convenience of not needing to remember bringing my tablet to animate when I go somewhere, and can use an animation app mouse free, so I don't have to set up on a table or something like that.

**Comment by artisteacher** [comment]
In preferences, you can enable touch gestures.
