### ISSUE TITLE
1.1 crashes on open on other user accounts

### ISSUE THREAD

**Issue by artisteacher** [turtletooth/tahoma2d#463]
**Describe the bug**
Tahoma2D opens just fine for the user that installs it. It crashes on open for other users.

**To Reproduce**
List steps to reproduce the behavior.
1. Install Tahoma2D in Applications with an admin account
2. Open Tahoma
3. Logout and  login to a different user account
4. Launch Tahoma

**Expected behavior**
Tahoma to open

**Screenshots**
<img width="857" alt="Screen Shot 2020-11-05 at 3 26 14 PM" src="https://user-images.githubusercontent.com/21159116/98293309-1691ed00-1f7c-11eb-9dd6-3cd2effe7777.png">

**Device Information:**
 - OS: macOS Catalina
 - Tahoma2D Version: 1.1

**Comment by jeremybullock** [comment]
This looks like a permissions thing.

**Comment by manongjohn** [comment]
The stuff folder doesn't have the right permissions.  I'll have to fix the packaging script to fix that.

In the meantime, please open terminal and navigate into the Tahoma2D.app folder then type: chmod 777 -R tahomastuff

That should correct it for now.

**Comment by artisteacher** [comment]
Thanks! Will do.
