### ISSUE TITLE
About the Raster level

### ISSUE THREAD

**Issue by Bandzia** [turtletooth/tahoma2d#464]
Hi!
So far so good the program has been great! Especially on the vector level.
But I gotta ask about the raster level, it seems like the issue is there when I used opentoonz, when I zoom out the line loose quality and I'm just asking if you are planning to fix that, it's just little bit irritating since other raster based programs don't do that. I know that after exporting the files it doesn't do that anymore.
But so far so good the program has been a blast other then that, I'm recommending it to all my friends right now.
Kindest Regards, Pat

**Comment by artisteacher** [comment]
I've had different experiences with the view of the line quality depending on the computer that I use. On an 8 year old iMac, I would see poor line quality dependent on the zoom. My MacBook Pro doesn't have that issue.

**Comment by jrhyme** [comment]
@Bandzia This is an unsolvable problem, since the code of this level is written in a similar way, for a special cartoon style. Alas, you will have to accept.

**Comment by jeremybullock** [comment]
The raster level line quality can be a little off when the viewer is zoomed in or out.  When viewed at 100% it will (should) give an accurate image.
