### ISSUE TITLE
When rendering a preview and/or rendering to mp4, there is nothing but a blank white screen.

### ISSUE THREAD

**Issue by justananimator** [turtletooth/tahoma2d#465]
The title says it all. When I go to render my project, either using preview or fast render to mp4, he product is a blank white screen. The audio still plays, but everything else is completely gone. I have both restarted my computer and reopened the scene, but nothing seems to work and the render still seems to be broken.

**Comment by artisteacher** [comment]
There are a couple things to check:
1. Is render visibility on for the layers in the Timeline (eye icon)
2. Are the layer nodes connected to the scene and output in the FX schematic?
<img width="249" alt="Screen Shot 2020-11-06 at 7 00 32 PM" src="https://user-images.githubusercontent.com/21159116/98425242-706ce280-2062-11eb-8e4f-b576bcf66570.png">

**Comment by justananimator** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/74079615/98428439-7c12d600-206f-11eb-9472-2c43676089bf.png)

Thanks, connecting it to the output did work. I never changed this, and I have never used the FX tab, but when I opened it there were two outputs. It was only connected to one. I'm not sure how or why this happened, but it's fixed now.

**Comment by artisteacher** [comment]
Weird. I'm glad that worked!
