### ISSUE TITLE
Vector erasers

### ISSUE THREAD

**Issue by semibala16** [turtletooth/tahoma2d#466]
A vector eraser would be amazing in Tahoe’s. It’s a eraser that erases lines on the outside of lineart. I know there’s a tool for it but it’s more frustrating to use. A vector eraser would make it so much easier.

**Comment by artisteacher** [comment]
Have you tried setting the eraser type to segment? Then you can just click and drag through the segments you want to erase.

**Comment by artisteacher** [comment]
Additionally, if you have vector strokes selected, you can right-click in the viewer and choose "remove vector overflow".

**Comment by jeremybullock** [comment]
As @artisteacher mentioned, this is already included in the segment mode of the eraser.
