### ISSUE TITLE
Copy and paste in diferent colors (Example inside November 9)

### ISSUE THREAD

**Issue by F-Burning** [turtletooth/tahoma2d#469]
Hi!

I do not know who I am addressing or where this message will be sent, but I would like to refer to who is responsible for all this in the first place:

Thank so much for this amazing work you are doing for people!

I would like to make a suggestion about colors. It would love to select a drawing in column A for example, and paste in column B, but in the color style that I have selected in column B, for example green. 

Always an option to fill colors between different levels, like in other painting softwares. For example when you select the fill tool, check an option like 'Fill between layers' for example, and the only thing that this do is take the reference of the lines on the screen, and fill that areas in the layer you want.

Hope you can implement this in a near future, because this makes the program absolutely perfect!

Again, thank you soooo much for all your work and dedication : )

Have a good day and greetings!

**Comment by F-Burning** [comment]
For example an option like this in animate tool that copy only the color selected...
 

![](https://i.postimg.cc/9f3vPhSt/image.png)

...and when you paste it in another column, this goes to the same color, or it create the same style automatically.

This can be made in CSP for example, or in RETAS Studio, and takes anime-style cleaning for example to another level, and never better said!

**Comment by jeremybullock** [comment]
Thank you for the kind words.  Unfortunately I think the requests here are beyond the scope of what I have in mind for the program.  I'm sorry for not being able to implement this.
