### ISSUE TITLE
Linux AppImage crashes on launch with Segfault

### ISSUE THREAD

**Issue by nvmb3rth30ry** [turtletooth/tahoma2d#471]
**Describe the bug**
At launch, after briefly displaying the Tahoma logo splash, the application crashes with a Segmentation fault.
Generally have no issues with AppImage binaries on my system.

**To Reproduce**
1. Change to local Tahoma directory
2. Run application
3. Wait (briefly)

**Expected behavior**
The application should display the workspace screen area, tool panel and interactive timeline (as normal).

**Screenshots**
Command line error messages at runtime:
```
amc@tuber:~/Soft/Tahoma2D$ ./Tahoma2D.AppImage
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
plugin search directory:/home/anders/Soft/Tahoma2D/tahomastuff/plugins
walkDirectory_: /home/anders/Soft/Tahoma2D/tahomastuff/plugins
===== PluginLoadController::finished() =====
QLayout: Attempting to add QLayout "" to MainWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to MainWindow "", which already has a layout
Segmentation fault (core dumped)
```

**Device Information:**
 - OS: Ubuntu 18.04.5 LTS
 - Tahoma2D Version: 1.1 Linux AppImage
 - GPU: NVIDIA RTX 2060
 - GPU Driver Version: 450.80.02

**Comment by manongjohn** [comment]
I don't seem to have this issue on my Ubuntu 18.04.4 LTS VM.

I did a quick search on-line and found this: https://askubuntu.com/questions/541343/problems-with-libgl-fbconfigs-swrast-through-each-update

Not sure if the solution proposed there would help you.

**Comment by nvmb3rth30ry** [comment]
Thanks, í will try this out!
AC

**Comment by nvmb3rth30ry** [comment]
Hey this issue has been fixed, I'm going to close it now.
The problem I think **was my nVidia driver** which was running but in a not-OK state on my system. I was getting some other strangeness so I installed a fresh driver (455) and now Tahoma is working brilliantly. My bad! Looking forward to doing some cool stuff with it.

**Comment by nvmb3rth30ry** [comment]
Closing, as explained above.
