### ISSUE TITLE
Annotation Columns in Xsheet

### ISSUE THREAD

**Issue by KaviG4** [turtletooth/tahoma2d#473]
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

Annotation Columns in Xsheet like a toonboom and Tvpaint

**Comment by artisteacher** [comment]
Are the note levels similar? I haven’t used toonboom or tvpaint, so I’m not sure what you are looking for. Note levels can be added from the Levels menu.

**Comment by jeremybullock** [comment]
This is not really feasible with how the xsheet and timeline are currently coded.  I agree that it would be nice.
