### ISSUE TITLE
More Simple and Usable Gradient Option

### ISSUE THREAD

**Issue by erayzesen** [turtletooth/tahoma2d#475]
Hi all. 

We could easily create gradients in Adobe flash (now adobe animate). In Tahoma we make this in a very primitive way. It would be nice if a setting like this was added and the gradient option became a standard.

The Gradient Sample in Flash;
https://youtu.be/Isa_RPPZ-JY?t=78

**Comment by artisteacher** [comment]
I like how gradients are handled in Affinity Designer better. The gradient tool is so flexible!

**Comment by erayzesen** [comment]
> I like how gradients are handled in Affinity Designer better. The gradient tool is so flexible!

It can be that way too. But the software will  need to new gradient tool in the tool bar for your idea. 

But it is simpler to adapt the example in flash to tahoma. But I can gladly accept this idea you gave if they can do this : )

**Comment by jeremybullock** [comment]
Unfortunately, I'm not sure how realistic this idea is with how Tahoma handles fills.  On vector and smart raster levels, fills aren't actually objects, they are just areas tagged with a color.  So getting more precise and specific gradients would actually be pretty challenging.
