### ISSUE TITLE
All tools behave as though they are the hand tool.

### ISSUE THREAD

**Issue by RinzyR** [turtletooth/tahoma2d#477]
**Describe the bug**
All of the tools appear to be behaving as though they are the hand tool. Often, they will leave a single "stamp" of the tool being used (ex: brush tool will leave a single dot) before performing hand tool operation. It isn't always immediate; sometimes drawing or erasing will work just fine, but after a few strokes, it will return to this behavior. It will also occasionally "fix" itself for a few minutes after typing in another window, or by swapping to a tool in a different category (ex: from brush or eraser tool to the pump tool) and back. However, even when it appears to fix itself, it will return to the described behavior sometimes within a few strokes.

**To Reproduce**
List steps to reproduce the behavior.
1. Open a scene.
2. Create a new raster level.
3. Attempt to draw on said raster layer using a tablet pen for more than a few pen strokes.

**Expected behavior**
The brush tool to create lines and eraser tool to remove pixels rather than move the canvas around.

**Screenshots**
I do not have any screenshots.

**Device Information:**
 - OS: Windows 10
 - Tahoma2D Version: 1.1
 - GPU: AMD Radeon RX 570
 - GPU Driver Version: 20.4.2
- Tablet: Huion Kamvas GT-191 (v1)
- Tablet Driver Version: v14.8.166.1482

**Comment by manongjohn** [comment]
If you haven't tried this yet, enable `Preferences -> Touch/Tablet Settings -> Enable Windows Ink Support` then restart Tahoma.

**Comment by RinzyR** [comment]
> If you haven't tried this yet, enable `Preferences -> Touch/Tablet Settings -> Enable Windows Ink Support` then restart Tahoma.

Ahah, forgive my surprise, but I believe you are also trying to help me on the OT subreddit! Unfortunately, as you already know then, that did not fix the problem for me.

**Comment by manongjohn** [comment]
Lol. Yes that's me 😄. I wasn't sure if it was you or not since the descriptions and what you tried were listed on reddit and not here. I went with this might be someone else just in case.

**Comment by manongjohn** [comment]
@RinzyR Since you stated on reddit that the issue resolved itself after you updated your graphic card driver and/or in combination with a Win10 update that also occured, I'm going to close this.
