### ISSUE TITLE
Tahoma interface changed entirely without warning.

### ISSUE THREAD

**Issue by justananimator** [turtletooth/tahoma2d#478]
I have no explanation for this. I opened Tahoma and the Timeline turned into an XSheet, the studio palette sort of appeared, my files seem to have been corrupted and the tab was renamed pitedit? I have encountered this issue once and simply redownloaded the software, but it happened again and I can only assume it is a bug.

![image](https://user-images.githubusercontent.com/74079615/98622474-9e0e9180-22d7-11eb-9016-2e3c83e22e75.png)

**Comment by artisteacher** [comment]
Are you using 1.1?

It looks like the Ghibli rooms somehow replaced the default rooms.

**Comment by jeremybullock** [comment]
What happens when you click Reset to Default Rooms in the Panels menu.  This will require a restart.

**Comment by jeremybullock** [comment]
The old Ghibli rooms are coded into the software and can appear if the program has trouble finding the standard room set.

**Comment by manongjohn** [comment]
This is one of those odd random bugs we've seen even in OT.

I think the old Ghibli rooms will show up if for some reason all the `profiles\users\xxx\layouts\Default\room#.ini` files are somehow deleted instead of being updated when quitting Tahoma.  I'm not sure what would cause that.

**Comment by jeremybullock** [comment]
This has been fixed.  Thanks @manongjohn
