### ISSUE TITLE
filling complex vector shapes

### ISSUE THREAD

**Issue by NitzanWeiner** [turtletooth/tahoma2d#480]
**Describe the bug**
hey,
1. after cleaning-up using the multiarc tool and removing some overlapping lines
I cant fill the shapes I made
2. there's no way to rejoin the lines and the fill tool won't fill it even if the maximum gap is maxed
the same thing happens 

I guess it's the same issue - there is no way to join vector lines and to fill them
not even with the tape tool or to maximize "maximum gup" in the fill tool

maybe it's a new feature - but for a new user that came from ToonBoom Harmony it a must-have

**To Reproduce**

1. make vector shape using multiarc
2. make an overlapping shape
3. remove overlapping lines
4. try to fill the shape

or

1. make a shape using multiarc
2. make a fully overlapping line
3. try to fill just one side of the shape

**Expected behavior**
the fill tool will be able to fill the shape

**Screenshots**
![image](https://user-images.githubusercontent.com/74252121/98691161-69054c00-2376-11eb-9c5b-26612204d327.png)

![image](https://user-images.githubusercontent.com/74252121/98691086-525ef500-2376-11eb-882d-fe8321757a9d.png)

**Device Information:**
 - OS: Windows
 - Tahoma2D Version: 1.1
 - GPU:  NVIDIA GTX 1060
 - GPU Driver Version: 27.21.14.5709

**Comment by jeremybullock** [comment]
Thanks for the bug report.  How are you erasing the overlapping lines?

**Comment by NitzanWeiner** [comment]
I'm using the cutter tool
But by make new node in the intersection and removing the overlapping nodes gets the same result

**Comment by beeheemooth** [comment]
I followed your steps and I have no problem with the fill. Do you have the Auto Group option enabled?

**Comment by NitzanWeiner** [comment]
Yes, i do have auto group enable

**Comment by beeheemooth** [comment]
turn it off

**Comment by artisteacher** [comment]
That's likely the problem. A shape is not considered truly "closed" if part of the shape is in a different group.

**Comment by NitzanWeiner** [comment]
Yea! That solve it.
But there is still an issue of join two vector lines
Is it possible?

**Comment by artisteacher** [comment]
Use the tape tool. You'll probably want the "Endpoint to Endpoint" mode.
