### ISSUE TITLE
Feature tweak? 

### ISSUE THREAD

**Issue by gracegloom101** [turtletooth/tahoma2d#481]
**Body Highlight**
When I use body highlight, I can't really change where the highlight could be coming from, only how many PX it has. I love this feature but I wish there was more elbow room for editing it

**What could be done?**
Maybe you could a rotation system for it? Where the high depends on the angle you want set for it? Oh and maybe you could have a mesh to edit where exactly you want the highlight to be
![VFX test1 0001-1](https://user-images.githubusercontent.com/46963266/98726439-20409980-235c-11eb-8395-3c9293591cf5.png)

**Comment by RodneyBaker** [comment]
We can definitely change where the light (and shadow if using the FX for that) is coming from.
Try entering a negative value to begin with and that should get you going in the right direction.  👍 

![image](https://user-images.githubusercontent.com/2576432/98830972-9dbde580-2400-11eb-819f-97076dd03a38.png)

I've changed the color to red here just to emphasize the change in direction.

What I like to do is add two Body Highlight FX... one for shadow and one for lighting.
I find it's usually best to have the shadow FX first and then pipe the output of that into the second (lighting) version of the effect.

**Comment by gracegloom101** [comment]
> We can definitely change where the light (and shadow if using the FX for that) is coming from.
> Try entering a negative value to begin with and that should get you going in the right direction. 👍
> 
> ![image](https://user-images.githubusercontent.com/2576432/98830972-9dbde580-2400-11eb-819f-97076dd03a38.png)
> 
> I've changed the color to red here just to emphasize the change in direction.
> 
> What I like to do is add two Body Highlight FX... one for shadow and one for lighting.
> I find it's usually best to have the shadow FX first and then pipe the output of that into the second (lighting) version of the effect.

Thank you!  I've done that but what if you only want the top to be lighted or like the character is under something that blocks out some of the light but not all of it? What do I do then?

**Comment by RodneyBaker** [comment]
> what if you only want the top to be lighted (as if the light is directly above said character) or the character is under something that blocks out some of the light but not all of it? What do I do then?


To get more realistic and effective lighting generally will take more complex setups of various nodes and effects all overlaid to either lighten or darken parts of the image.   This is basically what the Body Highlight FX is doing for us now but with less work, complexity and fine tuning capability.  

I know this will sound obvious but the basic idea is to add white (or lighter colors to areas in light and darker color to areas without light.  Different FX can then be used to adjust as needed... such as Multiplying one color over another to enhance a darkening effect.

Let's say your character was standing in an area where some window blinds cast shadows over his body/face.
A basic approach would be to create a new drawing with nothing but black and overlay that... adjusting the transparency as necessary.

This is basically what Body Highlight is doing... taking the outline of the current image... filling it in... then using that as the source to create a halo of color around that shape.

I suppose what I'm suggesting is that for more complex lighting cases Body Highlight FX likely will not be ideal.
It serves a specific and rather limited need and will work best with shapes that don't have complex outlines that hint at too much of the source shape.

**Comment by RodneyBaker** [comment]
Many different FX can be used to light a scene/character.
Here to do a quick example of window blinds falling over a character... I just grabbed a random effect... Hard Mix FX... but then added Distort FX and Blur FX to soften it...

![image](https://user-images.githubusercontent.com/2576432/98844496-006bad00-2412-11eb-9928-62f22c262357.png)

**Comment by RodneyBaker** [comment]
Returning to this part of your response for a moment:

> ...what if you only want the top to be lighted...

Body Highlight FX only uses what is made available so if a characters head is cropped off at the top... the resulting highlight will also have that crop.  Similarly, if the characters body ends where the camera stops at the bottom then we'll see that in the effect.
In this case what we likely want to do is keep the image going outside of the camera view so that the effect has something to use/project.   

Hope that makes sense.

**Comment by RodneyBaker** [comment]
Here's a super secret technique...

Make a clone (a second copy) of your character/image and then use that copy to drive the body highlight.
Then you can even place body highlights in the middle of the shape.

![image](https://user-images.githubusercontent.com/2576432/98846368-956fa580-2414-11eb-92de-fc4154b6d392.png)

Technically speaking we don't need the Body Highlight FX for that approach.
We can use another FX to overlay/blur and adjust to make our own body highlight effect.

**Comment by gracegloom101** [comment]
> Here's a super secret technique...
> 
> Make a clone (a second copy) of your character/image and then use that copy to drive the body highlight.
> Then you can even place body highlights in the middle of the shape.
> 
> ![image](https://user-images.githubusercontent.com/2576432/98846368-956fa580-2414-11eb-92de-fc4154b6d392.png)
> 
> Technically speaking we don't need the Body Highlight FX for that approach.
> We can use another FX to overlay/blur and adjust to make our own body highlight effect.
> 
> Disclaimer: I cannot remove the highlights you have already in the image so my posted images will also have those included.
> If you post a flat unlit image we'll be able to explore with a bit more detail.

I do have a flat unlit transparent png, hopefully this will help more?
![VFX test1 0001](https://user-images.githubusercontent.com/46963266/98852521-66116680-241d-11eb-8188-d3260c75a72a.png)

**Comment by RodneyBaker** [comment]
Here's a quick test basically trying to create my own Body Highlight flow using blur and multiply effects (with a copy of the source image driving the lighting):

![image](https://user-images.githubusercontent.com/2576432/98880389-41cd7e00-244d-11eb-8ce5-992aec02304f.png)


I'm definitely not satisfied with the results, especially in how long it would take to work this way for an animated sequence.

**Comment by gracegloom101** [comment]
> Here's a quick test basically trying to create my own Body Highlight flow using blur and multiply effects (with a copy of the source image driving the lighting):
> 
> ![image](https://user-images.githubusercontent.com/2576432/98880389-41cd7e00-244d-11eb-8ce5-992aec02304f.png)
> 
> I'm definitely not satisfied with the results, especially in how long it would take to work this way for an animated sequence.

Yeah definitely, I did figure out a way to sort make what I wanted to work. I create copy of the layer and use a matte with a linear gradient FX and it got closet to what I wanted
