### ISSUE TITLE
Tahoma2D.exe quarantined By Malwarebytes

### ISSUE THREAD

**Issue by Magic-Marco** [turtletooth/tahoma2d#485]
Hi
I have been trying out Tahoma 2d, and was just testing a simple bouncing ball animation when Malwarebytes suddenly decided that Tahoma2D.exe was Ransomware and quarantined it.
I downloaded Tahoma via tahoma2D.org a couple of days ago. I have also been running opentoonz for sometime now (but not more recently) and have not encountered similar problems.
It is most likely a false positive, but naturally I felt it should be reported and investigated.

Just to update I have been using opentoonz since reporting the above with no issues so far.
  
[MB_Report.txt](https://github.com/turtletooth/tahoma2d/files/5523834/MB_Report.txt)

**Comment by RodneyBaker** [comment]
Yes, sounds to be a false positive.
Over the past four years there have been quite a few reports similar to yours but thus far there hasn't been a single confirmed case of an actual virus/trojan.

**Comment by Magic-Marco** [comment]
Thanks I have removed Tahoma from quarantine and all seems ok

**Comment by jeremybullock** [comment]
I build Tahoma on my own machine.  I'll vouch for it.

**Comment by Magic-Marco** [comment]
Thanks I removed Tahoma from quarantine and all seems ok
