### ISSUE TITLE
Anim snippets

### ISSUE THREAD

**Issue by ladlon** [turtletooth/tahoma2d#491]
A useful feature might be the ability to select a section of cells (with translational and/or drawing keys) and save them into some easy to access 'snippet' library (hopefully keyboard mappable) for insertion into the timeline/xsheet as needed... similar to a copy to the clipboard, but where multiple snippets can be stored and retrieved).

This would be great for actions that occur multiple times within the timeline, like eye blinks, mouth roars, etc.  Click in the insertion point on the timeline, and select the snippet to insert.

**Comment by jeremybullock** [comment]
I'm going to close this for now since I'm not sure this will ever be on the roadmap.  It sounds useful, but there are so many things that need to happen first.
