### ISSUE TITLE
How to import settings from older version?

### ISSUE THREAD

**Issue by mjcairns** [turtletooth/tahoma2d#498]
Hi, I just downloaded Tahoma 1.1, and I'd like to copy my custom rooms, keyboard shortcuts, etc, over from the older version. Is there a way to do this?

**Comment by artisteacher** [comment]
Take a look at https://github.com/turtletooth/tahoma2d/pull/394 for the new locations. 1.2 will have a way to easily import.

**Comment by mjcairns** [comment]
Thank you!
