### ISSUE TITLE
Vector guide not working in timeline

### ISSUE THREAD

**Issue by jrhyme** [turtletooth/tahoma2d#502]
**Describe the bug**
The direction of vectors only works on the first stroke in the timeline.
**To Reproduce**
List steps to reproduce the behavior.
1. I draw the first frame, then I create empty ones, including the vector guide
2.  I turn on the onion skin and draw a stroke, where it shows the direction of the vector
3. After completing the quest, no more directions appear

**Expected behavior**
With each stroke made, there must be a new direction of vectors, it only works in level strip, when it should work and on a timeline like in opentoonz. 

**Screenshots**
![bandicam-2020-11-15-01-04-29-937](https://user-images.githubusercontent.com/49364531/99161445-29828b00-26fb-11eb-8642-46cf95d87d19.gif)

**Device Information:**
 - OS: [e.g. Windows]
 - Tahoma2D Version: [e.g. Nightly (2020-13-11)]
 - GPU: RX 580

**Comment by artisteacher** [comment]
I've run into this recently on macOS too, though it just happened one time. I might have been trying out the vector guided panel, but I'm not sure. The panel wasn't working the way I expected it to in general so I gave up using it for the time being.

**Comment by beeheemooth** [comment]
It seems that the display of the Vector Guide is not updated in the viewer, but only in the Level Strip. OT does not have this problem.

**Comment by jrhyme** [comment]
@beeheemooth I completely agree, I hope that they will fix it soon, as this panel will often be needed in the near future.
