### ISSUE TITLE
Keyframe Time Indicator Suggests 23 Seconds as 1 Minute

### ISSUE THREAD

**Issue by Mainman002** [turtletooth/tahoma2d#507]
The timeline scrubber doesn't fully estimate time correctly. It counts 23 frames (23 seconds) and then on the 24th frame it counts that as 1 minute. This makes it very hard to edit / cut time selections accurately. (My guess is that it's estimating time based on the fps value?)

**To Reproduce**
1. Add a keyframe that extends past 2 minutes
2. Scrub the timeline
3. Keep an eye on the bottom left of the preview window to see the time jump around to inaccurate values.

**Expected behavior**
Scrub along the timeline and the preview window updates to match the current frames time value (60 seconds = 1 minute instead of matching the fps value as it's difficult to edit with wrong time values)

**Screenshots**
![image](https://user-images.githubusercontent.com/11281480/99289943-44402700-2803-11eb-812f-94d04c6a51ba.png)

![image](https://user-images.githubusercontent.com/11281480/99289970-4f935280-2803-11eb-83a5-3acccbdefa33.png)

**Device Information:**
 - OS: Windows 10
 - Tahoma2D Version:  (2020-10-15)
 - Intel Core i3 Laptop

**Comment by jeremybullock** [comment]
Hi there.  The first values of the timecode are frames, not seconds.
So after 23 frames, 1 second is correct.
The order of the timecode is minutes:seconds:frames.

But looking at this did let me find a bug in how seconds were showing after the 1 minute mark.  So thank you.

**Comment by Mainman002** [comment]
No prob man :) it kept jumping around and it got kind of confusing to read xD
