### ISSUE TITLE
Tohoma2D won't start

### ISSUE THREAD

**Issue by Hedgehogmad** [turtletooth/tahoma2d#512]
I have just downloaded the software and followed the instructuins to install the program but it won't start the program, it will come up with a screen saying its starting up Tohoma then it dies and nothing happens, i have a pretty decent PC and no error messages pop up when it fails to load

**Comment by artisteacher** [comment]
Are you on Windows? Try opening "Event Viewer" and see if you can find an error message there for Tahoma. I don't have a pc, so I'm not sure of the specifics but it looks like you need to look at "Windows Logs -> Applications".

**Comment by Hedgehogmad** [comment]
this is what is showing in event viewer

Faulting application name: Tahoma2D.exe, version: 0.0.0.0, time stamp: 0x5f9b9536
Faulting module name: ucrtbase.dll, version: 10.0.18362.1110, time stamp: 0xb4cacc38
Exception code: 0xc0000409
Fault offset: 0x000000000006dace
Faulting process ID: 0x1cec
Faulting application start time: 0x01d6bce65271b48a
Faulting application path: C:\Program Files\Tahoma2D\Tahoma2D.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report ID: af5b48a3-a8b3-4230-a080-94c1c1c59429
Faulting package full name: 
Faulting package-relative application ID:

**Comment by jeremybullock** [comment]
I don't recommend putting it in "Program Files."

What happens when you move the Tahoma2D folder to your desktop or another location?

**Comment by Hedgehogmad** [comment]
i took it out of program files and it seems to work now thank you for the fix 👍

**Comment by jeremybullock** [comment]
Glad to help.
