### ISSUE TITLE
PROBLEMS TO OPEN OPENTOONS

### ISSUE THREAD

**Issue by elpanchitodelp** [turtletooth/tahoma2d#517]
THE BUG:  initially, the program didn´t open because i didn´t have installed something called "vulkan ddl1". the program itself told me that i could solve this problem by reinstalling the program, so i did it, but it dind´t work and the the same problem was there. so, i installed by myself this component called "vulkan ddl1", and i thought that the problem would be fixed, but when i tried to open it, a new problem apeared. the program said something like "ffmpeg.exe-the entry point is not found", and below of it, it says that the "entry point of the proces vkCreateDescriptorUpdateTemplate in the library of dynamic links.. (and it shows the route where, i think, some things of the program should be) wasn´t found". despite of this opentoons open, and i can use it, but if i try to work with a saved project, the frames that i´ve used are empty, but they appear like they have been covered, like in red color. i don´t know how to solve this, and i´m very worried about it.

Hola, el programa me esta fallando. en un principio porque no andaba el vulkan ddl1, y me el mismo programa me expecificaba que podia resolver este problema reinstalando el programa. hice eso mismo, pero cuando lo trato de abrir me aparece el mismo error, por lo tanto descargo el vulkan ddl1. pensé que asi podría resolver el problema, pero cuando voy a abrir el programa, nuevamente me salta un error que dice que no se encuentra el vkCreateDescriptorUpdateTemplate en la biblioteca de vinculos dinamicos. busque en internet a ver que signifcaba esto, pero no encuentro ninguna solucion. hay alguien que le haya sucedido lo mismo y lo haya solucionado?
aun asi el programa termina abriendo, pero cuando trato de abrir un proyecto guardado, me aparece en la linea de tiempo que los fotogramas fueron cubiertos, pero están en rojo porque no hay dibujos en ellos

**Device Information:**
 - OS: Windows
opentoons[
![WhatsApp Image 2020-11-18 at 9 22 12 PM](https://user-images.githubusercontent.com/74688770/99604414-34cc0400-29e4-11eb-8518-508633b7196d.jpeg)

**Comment by artisteacher** [comment]
Did you try to open Tahoma or OpenToonz? If it was OpenToonz, you should post [your issue here](https://github.com/opentoonz/opentoonz/issues).

**Comment by elpanchitodelp** [comment]
> Did you try to open Tahoma or OpenToonz? If it was OpenToonz, you should post [your issue here](https://github.com/opentoonz/opentoonz/issues).

okay

**Comment by artisteacher** [comment]
This can probably be closed.
