### ISSUE TITLE
Use column parent's color in column header

### ISSUE THREAD

**Issue by WolfInABowl** [turtletooth/tahoma2d#91]
1: Default | 2, 3, 4: Examples with different parents
![Column Parent Colors](https://user-images.githubusercontent.com/42905003/87902850-896d6b80-ca52-11ea-8865-80501458473f.png)

I believe that this would improve at-a-glance readability and would compliment the recent addition of the ability to change a column's parent in the XSheet.

**Comment by jeremybullock** [comment]
I'm going to look into this.  I'd love to add the ability to change a layers parent from the timeline view too.  Any idea on where that control might go?

**Comment by artisteacher** [comment]
You could add a new control on the far right of the layer name.
<img width="293" alt="Screen Shot 2020-09-16 at 9 14 52 PM" src="https://user-images.githubusercontent.com/21159116/93408218-0144f000-f862-11ea-81ab-cffb9a4f6ded.png">

**Comment by jeremybullock** [comment]
Closing with pending PR.
