### ISSUE TITLE
Make selected column layer more visible

### ISSUE THREAD

**Issue by DoctorRyan** [turtletooth/tahoma2d#98]
It has been requested if there is somewhere within Tahoma that we can add a place to display what current level is being worked on to avoid confusion.  One suggestion is to place this at the bottom of the viewer in the toolbar and have a  toggle in the sandwich menu.  Any other suggestions about where to place it?

**Comment by manongjohn** [comment]
The viewer tool bar already shows the current the level and level frame # you are working on

Example:  `[SCENE]: testscene   ::   Frame: 1   ::   Level: C.1   ::   Zoom : 100%`

The level you are also on is in the status bar at the bottom.

Example:  `Scene: testscene   |   15 Frames    |   Level: C   |  Selected: 1 frame : 1 column`

I disagree with adding to the viewer toolbar.  Beyond that the information doesn't quite make sense to me there, on smaller screens, it can get truncated.

**Comment by artisteacher** [comment]
I think having the level named in 2 places is fine. Though the styling for the active layer/column/level could be adjusted for better clarity on what is active. If the layer/column is selected, the color is often very similar to the raster blue. This is not as helpful at a quick glance - especially when toggling to the Xsheet orientation.

**Comment by manongjohn** [comment]
Forgive me as I'm not entirely sure where the confusion is coming from.  I suppose I'm so familiar with OT I know there are a number of visual clues to determine what I'm on, but likely overlooked by new users.

Assuming 1 level per column, the name of the column is suppose to change color, but the color is currently yellow so it's barely noticeable.   I normally need to change it to a different color like Cyan so it stands out more against the current level color scheme.

What might be more helpful is changing the xsheet's current cell indicator, the black box, so you know where you are on the xsheet as it can easily be overlooked.  It could stand to be a bit more obvious by making it a bit thicker and maybe changing to a different color other than black but not too close to when selecting a populated cell to move which is a thicker blue box.

**Comment by artisteacher** [comment]
I'm not particularly confused myself, but I can see how some would be. On small screens, toggling the Timeline to the Xsheet might show something like this - where just the header is visible & not any rows:
<img width="225" alt="Screen Shot 2020-07-24 at 12 19 19 PM" src="https://user-images.githubusercontent.com/21159116/88412761-0fb5e480-cda8-11ea-945f-3340accec677.png">
With the vector column active, the color is fairly similar to the raster blue. I can see the difference, but some people don't notice subtle color shifts & might not.

I'm also a fan of cyan for the active column name. It stands out a little more.

**Comment by DoctorRyan** [comment]
The request was from someone on OT Discord.  I agree I do not have much
confusion myself.  Hense, I was wanting to see what the rest of comminity
thought about it.  Thanks for the feedback.

**Comment by jeremybullock** [comment]
I think this was somewhat fixed with konero's fixes.
